# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/duration_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferDurationDurationTest < Minitest::Test
  include WaferMatchers

  # duration_corpus.rs:43
  def test_duration_1_second
    assert_duration "one sec", 1, :second
    assert_duration "1 second", 1, :second
    assert_duration "1\"", 1, :second
  end

  # duration_corpus.rs:51
  def test_duration_2_minutes
    assert_duration "2 mins", 2, :minute
    assert_duration "two minutes", 2, :minute
    assert_duration "2'", 2, :minute
    assert_duration "2 more minutes", 2, :minute
    assert_duration "two additional minutes", 2, :minute
    assert_duration "2 extra minutes", 2, :minute
    assert_duration "2 less minutes", 2, :minute
    assert_duration "2 fewer minutes", 2, :minute
    assert_duration "2m", 2, :minute
    assert_duration "2 m", 2, :minute
  end

  # duration_corpus.rs:66
  def test_duration_30_days
    assert_duration "30 days", 30, :day
  end

  # duration_corpus.rs:72
  def test_duration_7_weeks
    assert_duration "seven weeks", 7, :week
  end

  # duration_corpus.rs:78
  def test_duration_1_month
    assert_duration "1 month", 1, :month
    assert_duration "a month", 1, :month
  end

  # duration_corpus.rs:85
  def test_duration_3_quarters
    assert_duration "3 quarters", 3, :quarter
  end

  # duration_corpus.rs:91
  def test_duration_2_years
    assert_duration "2 years", 2, :year
  end

  # duration_corpus.rs:97
  def test_duration_half_hour
    assert_duration "half an hour", 30, :minute
    assert_duration "half hour", 30, :minute
    assert_duration "1/2 hour", 30, :minute
    assert_duration "1/2h", 30, :minute
    assert_duration "1/2 h", 30, :minute
  end

  # duration_corpus.rs:107
  def test_duration_half_day
    assert_duration "half a day", 12, :hour
    assert_duration "half day", 12, :hour
    assert_duration "1/2 day", 12, :hour
  end

  # duration_corpus.rs:115
  def test_duration_90_minutes
    assert_duration "an hour and a half", 90, :minute
    assert_duration "one hour and half", 90, :minute
    assert_duration "1 hour thirty", 90, :minute
    assert_duration "1 hour and thirty", 90, :minute
    assert_duration "1.5 hours", 90, :minute
    assert_duration "1.5 hrs", 90, :minute
    assert_duration "one and two quarter hour", 90, :minute
    assert_duration "one and two quarters hour", 90, :minute
    assert_duration "one and two quarter of hour", 90, :minute
    assert_duration "one and two quarters of hour", 90, :minute
  end

  # duration_corpus.rs:130
  def test_duration_75_minutes
    assert_duration "1 hour fifteen", 75, :minute
    assert_duration "1 hour and fifteen", 75, :minute
    assert_duration "one and quarter hour", 75, :minute
    assert_duration "one and a quarter hour", 75, :minute
    assert_duration "one and one quarter hour", 75, :minute
    assert_duration "one and quarter of hour", 75, :minute
    assert_duration "one and a quarter of hour", 75, :minute
    assert_duration "one and one quarter of hour", 75, :minute
  end

  # duration_corpus.rs:143
  def test_duration_130_minutes
    assert_duration "2 hours ten", 130, :minute
    assert_duration "2 hour and 10", 130, :minute
  end

  # duration_corpus.rs:150
  def test_duration_3615_seconds
    assert_duration "1 hour fifteen seconds", 3615, :second
    assert_duration "1 hour and fifteen seconds", 3615, :second
  end

  # duration_corpus.rs:157
  def test_duration_45_days
    assert_duration "a month and a half", 45, :day
    assert_duration "one month and half", 45, :day
  end

  # duration_corpus.rs:164
  def test_duration_27_months
    assert_duration "2 years and 3 months", 27, :month
    assert_duration "2 years, 3 months", 27, :month
    assert_duration "2 years 3 months", 27, :month
  end

  # duration_corpus.rs:172
  def test_duration_complex_seconds
    assert_duration "1 year, 2 days, 3 hours and 4 seconds", 31719604, :second
    assert_duration "1 year 2 days 3 hours and 4 seconds", 31719604, :second
  end

  # duration_corpus.rs:179
  def test_duration_330_seconds
    assert_duration "5 and a half minutes", 330, :second
    assert_duration "five and half min", 330, :second
    assert_duration "5 and an half minute", 330, :second
  end

  # duration_corpus.rs:187
  def test_duration_105_minutes
    assert_duration "one and three quarter hour", 105, :minute
    assert_duration "one and three quarters hour", 105, :minute
    assert_duration "one and three quarter of hour", 105, :minute
    assert_duration "one and three quarters of hour", 105, :minute
    assert_duration "one and three quarter of hours", 105, :minute
    assert_duration "one and three quarters of hours", 105, :minute
  end

  # duration_corpus.rs:198
  def test_duration_135_minutes
    assert_duration "two and quarter hour", 135, :minute
    assert_duration "two and a quarter of hour", 135, :minute
    assert_duration "two and quarter of hours", 135, :minute
    assert_duration "two and a quarter of hours", 135, :minute
  end

  # duration_corpus.rs:207
  def test_duration_hour_45_minutes
    assert_duration "an hour and 45 minutes", 105, :minute
    assert_duration "one hour and 45 minutes", 105, :minute
  end

  # duration_corpus.rs:214
  def test_duration_90_seconds
    assert_duration "a minute and 30 seconds", 90, :second
    assert_duration "one minute and 30 seconds", 90, :second
  end

  # duration_corpus.rs:221
  def test_duration_3630_seconds
    assert_duration "an hour and 30 seconds", 3630, :second
  end

  # duration_corpus.rs:227
  def test_duration_930_seconds
    assert_duration "15.5 minutes", 930, :second
    assert_duration "15.5 minute", 930, :second
    assert_duration "15.5 mins", 930, :second
    assert_duration "15.5 min", 930, :second
  end
end
