# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/duration_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferDurationNoDurationTest < Minitest::Test
  include WaferMatchers

  # duration_corpus.rs:236
  def test_duration_negative_for_months
    assert_no_duration "for months"
  end

  # duration_corpus.rs:241
  def test_duration_negative_in_days
    assert_no_duration "in days"
  end

  # duration_corpus.rs:246
  def test_duration_negative_secretary
    assert_no_duration "secretary"
  end

  # duration_corpus.rs:251
  def test_duration_negative_minutes_alone
    assert_no_duration "minutes"
  end

  # duration_corpus.rs:256
  def test_duration_negative_i_second_that
    assert_no_duration "I second that"
  end
end
