# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/amount_of_money_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferAmountOfMoneyMoneyTest < Minitest::Test
  include WaferMatchers

  # amount_of_money_corpus.rs:48
  def test_money_1_dollar
    assert_money "$1", 1.0, "USD"
    assert_money "one dollar", 1.0, "USD"
    assert_money "a dollar", 1.0, "USD"
  end

  # amount_of_money_corpus.rs:56
  def test_money_10_dollars
    assert_money "$10", 10.0, "USD"
    assert_money "$ 10", 10.0, "USD"
    assert_money "10$", 10.0, "USD"
    assert_money "10 dollars", 10.0, "USD"
    assert_money "ten dollars", 10.0, "USD"
  end

  # amount_of_money_corpus.rs:66
  def test_money_10_cents
    assert_money "10 cent", 10.0, "cent"
    assert_money "ten pennies", 10.0, "cent"
    assert_money "ten cents", 10.0, "cent"
    assert_money "10 c", 10.0, "cent"
    assert_money "10¢", 10.0, "cent"
  end

  # amount_of_money_corpus.rs:76
  def test_money_10k_dollars
    assert_money "$10K", 10000.0, "USD"
    assert_money "10k$", 10000.0, "USD"
    assert_money "$10,000", 10000.0, "USD"
  end

  # amount_of_money_corpus.rs:84
  def test_money_usd_3_14
    assert_money "USD3.14", 3.14, "USD"
    assert_money "3.14US$", 3.14, "USD"
    assert_money "US$ 3.14", 3.14, "USD"
    assert_money "US$3 and fourteen", 3.14, "USD"
  end

  # amount_of_money_corpus.rs:93
  def test_money_20_euros
    assert_money "20€", 20.0, "EUR"
    assert_money "20 euros", 20.0, "EUR"
    assert_money "20 Euro", 20.0, "EUR"
    assert_money "20 Euros", 20.0, "EUR"
    assert_money "EUR 20", 20.0, "EUR"
    assert_money "EUR 20.0", 20.0, "EUR"
    assert_money "20€", 20.0, "EUR"
    assert_money "20 €ur", 20.0, "EUR"
  end

  # amount_of_money_corpus.rs:106
  def test_money_10_pounds
    assert_money "£10", 10.0, "GBP"
    assert_money "ten pounds", 10.0, "GBP"
  end

  # amount_of_money_corpus.rs:113
  def test_money_20_inr
    assert_money "Rs. 20", 20.0, "INR"
    assert_money "Rs 20", 20.0, "INR"
    assert_money "20 Rupees", 20.0, "INR"
    assert_money "20Rs", 20.0, "INR"
    assert_money "Rs20", 20.0, "INR"
  end

  # amount_of_money_corpus.rs:123
  def test_money_20_43_inr
    assert_money "20 Rupees 43", 20.43, "INR"
    assert_money "twenty rupees 43", 20.43, "INR"
  end

  # amount_of_money_corpus.rs:130
  def test_money_20_43_dollars
    assert_money "$20 and 43c", 20.43, "USD"
    assert_money "$20 43", 20.43, "USD"
    assert_money "20 dollar 43c", 20.43, "USD"
    assert_money "20 dollars 43 cents", 20.43, "USD"
    assert_money "twenty dollar 43 cents", 20.43, "USD"
    assert_money "20 dollar 43", 20.43, "USD"
    assert_money "twenty dollar and 43", 20.43, "USD"
  end

  # amount_of_money_corpus.rs:142
  def test_money_gbp_3_01
    assert_money "GBP3.01", 3.01, "GBP"
    assert_money "GBP 3.01", 3.01, "GBP"
    assert_money "3 GBP 1 pence", 3.01, "GBP"
    assert_money "3 GBP and one", 3.01, "GBP"
  end

  # amount_of_money_corpus.rs:151
  def test_money_cad_3_03
    assert_money "CAD3.03", 3.03, "CAD"
    assert_money "CAD 3.03", 3.03, "CAD"
    assert_money "3 CAD 3 cents", 3.03, "CAD"
  end

  # amount_of_money_corpus.rs:159
  def test_money_chf_3_04
    assert_money "CHF3.04", 3.04, "CHF"
    assert_money "CHF 3.04", 3.04, "CHF"
    assert_money "3 CHF 4 cents", 3.04, "CHF"
  end

  # amount_of_money_corpus.rs:167
  def test_money_cny_3
    assert_money "CNY3", 3.0, "CNY"
    assert_money "CNY 3", 3.0, "CNY"
    assert_money "3 CNY", 3.0, "CNY"
    assert_money "3 yuan", 3.0, "CNY"
  end

  # amount_of_money_corpus.rs:176
  def test_money_42_bucks
    assert_money "42 bucks", 42.0, "USD"
    assert_money "around 42 bucks", 42.0, "USD"
    assert_money "exactly 42 bucks", 42.0, "USD"
  end

  # amount_of_money_corpus.rs:184
  def test_money_42_kwd
    assert_money "42 KWD", 42.0, "KWD"
    assert_money "42 kuwaiti Dinar", 42.0, "KWD"
  end

  # amount_of_money_corpus.rs:191
  def test_money_42_lbp
    assert_money "42 LBP", 42.0, "LBP"
    assert_money "42 Lebanese Pounds", 42.0, "LBP"
  end

  # amount_of_money_corpus.rs:198
  def test_money_42_egp
    assert_money "42 EGP", 42.0, "EGP"
    assert_money "42 egyptianpound", 42.0, "EGP"
    assert_money "42 LE", 42.0, "EGP"
    assert_money "42 L.E", 42.0, "EGP"
    assert_money "42 l.e.", 42.0, "EGP"
    assert_money "42 le", 42.0, "EGP"
    assert_money "42 geneh", 42.0, "EGP"
    assert_money "42 genihat masriya", 42.0, "EGP"
  end

  # amount_of_money_corpus.rs:211
  def test_money_42_qar
    assert_money "42 QAR", 42.0, "QAR"
    assert_money "42 qatari riyals", 42.0, "QAR"
  end

  # amount_of_money_corpus.rs:218
  def test_money_42_sar
    assert_money "42 SAR", 42.0, "SAR"
    assert_money "42 Saudiriyal", 42.0, "SAR"
  end

  # amount_of_money_corpus.rs:225
  def test_money_42_bgn
    assert_money "42 BGN", 42.0, "BGN"
  end

  # amount_of_money_corpus.rs:231
  def test_money_42_myr
    assert_money "42 MYR", 42.0, "MYR"
    assert_money "42 RM", 42.0, "MYR"
    assert_money "RM 42", 42.0, "MYR"
    assert_money "MYR 42", 42.0, "MYR"
    assert_money "42MYR", 42.0, "MYR"
    assert_money "42RM", 42.0, "MYR"
    assert_money "RM42", 42.0, "MYR"
    assert_money "MYR42", 42.0, "MYR"
    assert_money "ringgit 42", 42.0, "MYR"
    assert_money "42 ringgit", 42.0, "MYR"
    assert_money "42 malaysia ringgit", 42.0, "MYR"
    assert_money "malaysia ringgit 42", 42.0, "MYR"
    assert_money "42 malaysian ringgit", 42.0, "MYR"
    assert_money "malaysian ringgit 42", 42.0, "MYR"
    assert_money "42 malaysia ringgits", 42.0, "MYR"
    assert_money "malaysia ringgits 42", 42.0, "MYR"
    assert_money "42 malaysian ringgits", 42.0, "MYR"
    assert_money "malaysian ringgits 42", 42.0, "MYR"
  end

  # amount_of_money_corpus.rs:254
  def test_money_myr_20_43
    assert_money "20 ringgit and 43c", 20.43, "MYR"
    assert_money "20 ringgit and 43 sen", 20.43, "MYR"
    assert_money "twenty ringgit 43 sens", 20.43, "MYR"
    assert_money "20 ringgit 43", 20.43, "MYR"
    assert_money "twenty ringgit and 43", 20.43, "MYR"
  end

  # amount_of_money_corpus.rs:264
  def test_money_10_dinars
    assert_money "10 dinars", 10.0, "dinar"
  end

  # amount_of_money_corpus.rs:270
  def test_money_10_ils
    assert_money "ten shekels", 10.0, "ILS"
    assert_money "10 ILS", 10.0, "ILS"
  end

  # amount_of_money_corpus.rs:277
  def test_money_10_riyals
    assert_money "ten riyals", 10.0, "riyal"
    assert_money "10 riyals", 10.0, "riyal"
  end

  # amount_of_money_corpus.rs:284
  def test_money_10_rials
    assert_money "ten rials", 10.0, "rial"
    assert_money "10 rials", 10.0, "rial"
  end

  # amount_of_money_corpus.rs:291
  def test_money_between_10_20_dollars
    assert_money "between 10 and 20 dollars", 10.0, "USD"
    assert_money "from 10 dollars to 20 dollars", 10.0, "USD"
    assert_money "around 10-20 dollars", 10.0, "USD"
    assert_money "between 10 dollars and 20 dollars", 10.0, "USD"
    assert_money "from 10 to 20 dollars", 10.0, "USD"
    assert_money "about $10-$20", 10.0, "USD"
    assert_money "10-20 dollars", 10.0, "USD"
  end

  # amount_of_money_corpus.rs:303
  def test_money_between_1_1_1_3_dollars
    assert_money "between 1.1 and 1.3 dollars", 1.1, "USD"
    assert_money "from 1 point 1 and one point three dollars", 1.1, "USD"
  end

  # amount_of_money_corpus.rs:310
  def test_money_under_7_eur
    assert_money "under seven euros", 7.0, "EUR"
    assert_money "less than 7 EUR", 7.0, "EUR"
    assert_money "lower than 7€", 7.0, "EUR"
    assert_money "no more than 7 euros", 7.0, "EUR"
    assert_money "at most 7€", 7.0, "EUR"
  end

  # amount_of_money_corpus.rs:320
  def test_money_above_1_42_dollars
    assert_money "more than 1 dollar and forty-two cents", 1.42, "USD"
    assert_money "at least $1.42", 1.42, "USD"
    assert_money "over 1.42 dollars", 1.42, "USD"
    assert_money "above a dollar and 42 cents", 1.42, "USD"
    assert_money "no less than $1.42", 1.42, "USD"
  end

  # amount_of_money_corpus.rs:330
  def test_money_5_lakh_rupees
    assert_money "5 lakh rupees", 500000.0, "INR"
    assert_money "five lakhs rupees", 500000.0, "INR"
  end

  # amount_of_money_corpus.rs:337
  def test_money_7_9_lakh_rupees
    assert_money "7-9 lakh rupees", 7.0, "INR"
  end

  # amount_of_money_corpus.rs:343
  def test_money_4_crore_rupees
    assert_money "four crore rupees", 40000000.0, "INR"
    assert_money "4 crores rupees", 40000000.0, "INR"
  end

  # amount_of_money_corpus.rs:350
  def test_money_10_mnt
    assert_money "ten tugriks", 10.0, "MNT"
    assert_money "10 Tugrik", 10.0, "MNT"
    assert_money "10MNT", 10.0, "MNT"
  end

  # amount_of_money_corpus.rs:358
  def test_money_usd_4_7_billion
    assert_money "US$4.7 billion", 4700000000.0, "USD"
    assert_money "a US$4.7 billion", 4700000000.0, "USD"
    assert_money "a US$ 4.7 billion", 4700000000.0, "USD"
  end

  # amount_of_money_corpus.rs:366
  def test_money_uah_3_04
    assert_money "UAH3.04", 3.04, "UAH"
    assert_money "UAH 3.04", 3.04, "UAH"
    assert_money "3 UAH 4 kopiykas", 3.04, "UAH"
  end
end
