# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/distance_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferDistanceDistanceTest < Minitest::Test
  include WaferMatchers

  # distance_corpus.rs:43
  def test_distance_3_km
    assert_distance "3 kilometers", 3.0, "kilometre"
    assert_distance "3 km", 3.0, "kilometre"
    assert_distance "3km", 3.0, "kilometre"
    assert_distance "3k", 3.0, "kilometre"
    assert_distance "3.0 km", 3.0, "kilometre"
  end

  # distance_corpus.rs:53
  def test_distance_8_miles
    assert_distance "8 miles", 8.0, "mile"
    assert_distance "eight mile", 8.0, "mile"
    assert_distance "8 mi", 8.0, "mile"
  end

  # distance_corpus.rs:61
  def test_distance_9m
    assert_distance "9m", 9.0, "m"
  end

  # distance_corpus.rs:67
  def test_distance_2_cm
    assert_distance "2cm", 2.0, "centimetre"
    assert_distance "2 centimeters", 2.0, "centimetre"
  end

  # distance_corpus.rs:74
  def test_distance_5_inches
    assert_distance "5 in", 5.0, "inch"
    assert_distance "5''", 5.0, "inch"
    assert_distance "five inches", 5.0, "inch"
    assert_distance "5\"", 5.0, "inch"
  end

  # distance_corpus.rs:83
  def test_distance_1_87_metres
    assert_distance "1.87 meters", 1.87, "metre"
  end

  # distance_corpus.rs:89
  def test_distance_composite_feet_inches
    assert_distance "7 feet and 10 inches", 94.0, "inch"
    assert_distance "7 feet, 10 inches", 94.0, "inch"
    assert_distance "7 feet 10 inches", 94.0, "inch"
  end

  # distance_corpus.rs:97
  def test_distance_composite_km_m
    assert_distance "2 km and 1 meter", 2001.0, "metre"
    assert_distance "2 kilometer, 1 metre", 2001.0, "metre"
    assert_distance "2 kilometer 1 metre", 2001.0, "metre"
  end

  # distance_corpus.rs:105
  def test_distance_composite_yards_feet_inches
    assert_distance "2 yards 7 ft 10 inches", 166.0, "inch"
    assert_distance "2 yds, 7 feet and 10 inches", 166.0, "inch"
    assert_distance "2 yards, 7 feet, 10 in", 166.0, "inch"
  end

  # distance_corpus.rs:113
  def test_distance_composite_yards_feet
    assert_distance "2 yards and 7 feet", 13.0, "foot"
    assert_distance "2 yards, 7 feet", 13.0, "foot"
    assert_distance "2 yd 7'", 13.0, "foot"
  end

  # distance_corpus.rs:121
  def test_distance_composite_km_m_cm
    assert_distance "10 kms 8 metres 6 cm", 1000806.0, "centimetre"
    assert_distance "10 kms, 8 meters, 6 cm", 1000806.0, "centimetre"
    assert_distance "10 kms, 8 meters and 6 centimeters", 1000806.0, "centimetre"
  end

  # distance_corpus.rs:133
  def test_distance_composite_m_ft
    assert_distance "1 meter and 1 foot", 1.3048, "metre"
  end

  # distance_corpus.rs:139
  def test_distance_composite_km_mi
    assert_distance "1 kilometer and 1 mile", 2.609344, "kilometre"
  end

  # distance_corpus.rs:145
  def test_distance_3m_ambiguous
    assert_distance "3m", 3.0, "m"
  end

  # distance_corpus.rs:151
  def test_distance_3m_5cm
    assert_distance "3m and 5cm", 305.0, "centimetre"
  end

  # distance_corpus.rs:157
  def test_distance_1m_1ft
    assert_distance "1m and 1ft", 5281.0, "foot"
  end

  # distance_corpus.rs:163
  def test_distance_range_3_5_km
    assert_distance "between 3 and 5 kilometers", 3.0, "kilometre"
    assert_distance "from 3km to 5km", 3.0, "kilometre"
    assert_distance "around 3-5 kilometers", 3.0, "kilometre"
    assert_distance "about 3km-5km", 3.0, "kilometre"
    assert_distance "3-5 kilometers", 3.0, "kilometre"
  end

  # distance_corpus.rs:173
  def test_distance_under_3_5_miles
    assert_distance "under 3.5 miles", 3.5, "mile"
    assert_distance "less than 3.5mi", 3.5, "mile"
    assert_distance "lower than three point five miles", 3.5, "mile"
  end

  # distance_corpus.rs:181
  def test_distance_above_5_inches
    assert_distance "more than five inches", 5.0, "inch"
    assert_distance "at least 5''", 5.0, "inch"
    assert_distance "over 5\"", 5.0, "inch"
    assert_distance "above 5 in", 5.0, "inch"
  end

  # distance_corpus.rs:190
  def test_distance_between_5_6_mm
    assert_distance "between 5 and six millimeters", 5.0, "millimetre"
    assert_distance "between 5 and six millimetres", 5.0, "millimetre"
    assert_distance "5-6 mm", 5.0, "millimetre"
  end
end
