# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/url_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferUrlNoUrlTest < Minitest::Test
  include WaferMatchers

  # url_corpus.rs:154
  def test_url_negative_foo
    assert_no_url "foo"
  end

  # url_corpus.rs:159
  def test_url_negative_myhost
    assert_no_url "MYHOST"
  end

  # url_corpus.rs:164
  def test_url_negative_hey_42
    assert_no_url "hey:42"
  end

  # url_corpus.rs:169
  def test_url_negative_25
    assert_no_url "25"
  end
end
