# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/url_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferUrlUrlTest < Minitest::Test
  include WaferMatchers

  # url_corpus.rs:42
  def test_url_http_www_bla
    assert_url "http://www.bla.com", "http://www.bla.com", "bla.com"
  end

  # url_corpus.rs:47
  def test_url_www_bla_port_path
    assert_url "www.bla.com:8080/path", "www.bla.com:8080/path", "bla.com"
  end

  # url_corpus.rs:52
  def test_url_https_myserver
    assert_url "https://myserver?foo=bar", "https://myserver?foo=bar", "myserver"
  end

  # url_corpus.rs:61
  def test_url_cnn_com
    assert_url "cnn.com/info", "cnn.com/info", "cnn.com"
  end

  # url_corpus.rs:66
  def test_url_bla_com_path
    assert_url "bla.com/path/path?ext=%23&foo=bla", "bla.com/path/path?ext=%23&foo=bla", "bla.com"
  end

  # url_corpus.rs:75
  def test_url_localhost
    assert_url "localhost", "localhost", "localhost"
  end

  # url_corpus.rs:80
  def test_url_localhost_port
    assert_url "localhost:8000", "localhost:8000", "localhost"
  end

  # url_corpus.rs:85
  def test_url_http_kimchi
    assert_url "http://kimchi", "http://kimchi", "kimchi"
  end

  # url_corpus.rs:90
  def test_url_https_500px
    assert_url "https://500px.com:443/about", "https://500px.com:443/about", "500px.com"
  end

  # url_corpus.rs:99
  def test_url_www2_foo_bar
    assert_url "www2.foo-bar.net?foo=bar", "www2.foo-bar.net?foo=bar", "foo-bar.net"
  end

  # url_corpus.rs:108
  def test_url_api_wit_ai
    assert_url "https://api.wit.ai/message?q=hi", "https://api.wit.ai/message?q=hi", "api.wit.ai"
  end

  # url_corpus.rs:117
  def test_url_amazon_co_uk
    assert_url "aMaZon.co.uk/?page=home", "aMaZon.co.uk/?page=home", "amazon.co.uk"
  end

  # url_corpus.rs:126
  def test_url_wikipedia
    assert_url "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax", "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax", "en.wikipedia.org"
  end

  # url_corpus.rs:135
  def test_url_example_csv
    assert_url "http://example.com/data.csv#cell=4,1-6,2", "http://example.com/data.csv#cell=4,1-6,2", "example.com"
  end

  # url_corpus.rs:144
  def test_url_example_webm
    assert_url "http://example.com/bar.webm#t=40,80&xywh=160,120,320,240", "http://example.com/bar.webm#t=40,80&xywh=160,120,320,240", "example.com"
  end
end
