# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeInstantTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:218
  def test_time_now
    assert_time_instant "now", [2013, 2, 12, 4, 30, 0], :second
    assert_time_instant "right now", [2013, 2, 12, 4, 30, 0], :second
    assert_time_instant "just now", [2013, 2, 12, 4, 30, 0], :second
    assert_time_instant "at the moment", [2013, 2, 12, 4, 30, 0], :second
    assert_time_instant "ATM", [2013, 2, 12, 4, 30, 0], :second
  end

  # time_corpus.rs:1184
  def test_time_in_a_sec
    assert_time_instant "in a sec", [2013, 2, 12, 4, 30, 1], :second
    assert_time_instant "one second from now", [2013, 2, 12, 4, 30, 1], :second
    assert_time_instant "in 1\"", [2013, 2, 12, 4, 30, 1], :second
  end

  # time_corpus.rs:1191
  def test_time_in_a_minute
    assert_time_instant "in a minute", [2013, 2, 12, 4, 31, 0], :second
    assert_time_instant "in one minute", [2013, 2, 12, 4, 31, 0], :second
    assert_time_instant "in 1'", [2013, 2, 12, 4, 31, 0], :second
  end

  # time_corpus.rs:1198
  def test_time_in_2_minutes
    assert_time_instant "in 2 minutes", [2013, 2, 12, 4, 32, 0], :second
    assert_time_instant "in 2 more minutes", [2013, 2, 12, 4, 32, 0], :second
    assert_time_instant "2 minutes from now", [2013, 2, 12, 4, 32, 0], :second
    assert_time_instant "in a couple of minutes", [2013, 2, 12, 4, 32, 0], :second
    assert_time_instant "in a pair of minutes", [2013, 2, 12, 4, 32, 0], :second
  end

  # time_corpus.rs:1211
  def test_time_in_three_minutes
    assert_time_instant "in three minutes", [2013, 2, 12, 4, 33, 0], :second
    assert_time_instant "in a few minutes", [2013, 2, 12, 4, 33, 0], :second
  end

  # time_corpus.rs:1217
  def test_time_in_60_minutes
    assert_time_instant "in 60 minutes", [2013, 2, 12, 5, 30, 0], :second
  end

  # time_corpus.rs:1222
  def test_time_in_quarter_of_an_hour
    assert_time_instant "in a quarter of an hour", [2013, 2, 12, 4, 45, 0], :second
    assert_time_instant "in 1/4h", [2013, 2, 12, 4, 45, 0], :second
    assert_time_instant "in 1/4 h", [2013, 2, 12, 4, 45, 0], :second
    assert_time_instant "in 1/4 hour", [2013, 2, 12, 4, 45, 0], :second
  end

  # time_corpus.rs:1234
  def test_time_in_half_an_hour
    assert_time_instant "in half an hour", [2013, 2, 12, 5, 0, 0], :second
    assert_time_instant "in 1/2h", [2013, 2, 12, 5, 0, 0], :second
    assert_time_instant "in 1/2 h", [2013, 2, 12, 5, 0, 0], :second
    assert_time_instant "in 1/2 hour", [2013, 2, 12, 5, 0, 0], :second
  end

  # time_corpus.rs:1242
  def test_time_in_three_quarters_of_an_hour
    assert_time_instant "in three-quarters of an hour", [2013, 2, 12, 5, 15, 0], :second
    assert_time_instant "in 3/4h", [2013, 2, 12, 5, 15, 0], :second
    assert_time_instant "in 3/4 h", [2013, 2, 12, 5, 15, 0], :second
    assert_time_instant "in 3/4 hour", [2013, 2, 12, 5, 15, 0], :second
  end

  # time_corpus.rs:1254
  def test_time_in_2_5_hours
    assert_time_instant "in 2.5 hours", [2013, 2, 12, 7, 0, 0], :second
    assert_time_instant "in 2 and an half hours", [2013, 2, 12, 7, 0, 0], :second
  end

  # time_corpus.rs:1260
  def test_time_in_one_hour
    assert_time_instant "in one hour", [2013, 2, 12, 5, 30, 0], :minute
    assert_time_instant "in 1h", [2013, 2, 12, 5, 30, 0], :minute
  end

  # time_corpus.rs:1266
  def test_time_in_a_couple_hours
    assert_time_instant "in a couple hours", [2013, 2, 12, 6, 30, 0], :minute
    assert_time_instant "in a couple of hours", [2013, 2, 12, 6, 30, 0], :minute
  end

  # time_corpus.rs:1272
  def test_time_in_a_few_hours
    assert_time_instant "in a few hours", [2013, 2, 12, 7, 30, 0], :minute
    assert_time_instant "in few hours", [2013, 2, 12, 7, 30, 0], :minute
  end

  # time_corpus.rs:1278
  def test_time_in_24_hours
    assert_time_instant "in 24 hours", [2013, 2, 13, 4, 30, 0], :minute
  end

  # time_corpus.rs:1283
  def test_time_in_a_day
    assert_time_instant "in a day", [2013, 2, 13, 4, 0, 0], :hour
    assert_time_instant "a day from now", [2013, 2, 13, 4, 0, 0], :hour
  end

  # time_corpus.rs:1289
  def test_time_a_day_from_right_now
    assert_time_instant "a day from right now", [2013, 2, 13, 4, 30, 0], :second
  end

  # time_corpus.rs:1317
  def test_time_in_7_days
    assert_time_instant "in 7 days", [2013, 2, 19, 4, 0, 0], :hour
  end

  # time_corpus.rs:1322
  def test_time_in_7_days_at_5pm
    assert_time_instant "in 7 days at 5pm", [2013, 2, 19, 17, 0, 0], :hour
  end

  # time_corpus.rs:1327
  def test_time_in_4_years_at_5pm
    assert_time_instant "in 4 years at 5pm", [2017, 2, 1, 17, 0, 0], :hour
  end

  # time_corpus.rs:1332
  def test_time_in_1_week
    assert_time_instant "in 1 week", [2013, 2, 19, 0, 0, 0], :day
    assert_time_instant "in a week", [2013, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:1338
  def test_time_in_about_half_an_hour
    assert_time_instant "in about half an hour", [2013, 2, 12, 5, 0, 0], :second
  end

  # time_corpus.rs:1343
  def test_time_7_days_ago
    assert_time_instant "7 days ago", [2013, 2, 5, 4, 0, 0], :hour
  end

  # time_corpus.rs:1348
  def test_time_14_days_ago
    assert_time_instant "14 days Ago", [2013, 1, 29, 4, 0, 0], :hour
    assert_time_instant "a fortnight ago", [2013, 1, 29, 4, 0, 0], :hour
  end

  # time_corpus.rs:1354
  def test_time_a_week_ago
    assert_time_instant "a week ago", [2013, 2, 5, 0, 0, 0], :day
    assert_time_instant "one week ago", [2013, 2, 5, 0, 0, 0], :day
    assert_time_instant "1 week ago", [2013, 2, 5, 0, 0, 0], :day
  end

  # time_corpus.rs:1367
  def test_time_three_weeks_ago
    assert_time_instant "three weeks ago", [2013, 1, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:1372
  def test_time_three_months_ago
    assert_time_instant "three months ago", [2012, 11, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:1397
  def test_time_two_years_ago
    assert_time_instant "two years ago", [2011, 2, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:1402
  def test_time_7_days_hence
    assert_time_instant "7 days hence", [2013, 2, 19, 4, 0, 0], :hour
  end

  # time_corpus.rs:1407
  def test_time_14_days_hence
    assert_time_instant "14 days hence", [2013, 2, 26, 4, 0, 0], :hour
    assert_time_instant "a fortnight hence", [2013, 2, 26, 4, 0, 0], :hour
  end

  # time_corpus.rs:1413
  def test_time_a_week_hence
    assert_time_instant "a week hence", [2013, 2, 19, 0, 0, 0], :day
    assert_time_instant "one week hence", [2013, 2, 19, 0, 0, 0], :day
    assert_time_instant "1 week hence", [2013, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:1420
  def test_time_three_weeks_hence
    assert_time_instant "three weeks hence", [2013, 3, 5, 0, 0, 0], :day
  end

  # time_corpus.rs:1425
  def test_time_three_months_hence
    assert_time_instant "three months hence", [2013, 5, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:1430
  def test_time_two_years_hence
    assert_time_instant "two years hence", [2015, 2, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:2885
  def test_time_4pm_cet
    assert_time_instant "4pm CET", [2013, 2, 12, 13, 0, 0], :minute
  end

  # time_corpus.rs:2890
  def test_time_thursday_8_gmt
    assert_time_instant "Thursday 8:00 GMT", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 8:00 gmt", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 8h00 GMT", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 8h00 gmt", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 8h GMT", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 8h gmt", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thu at 8 GMT", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thu at 8 gmt", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 9 am BST", [2013, 2, 14, 6, 0, 0], :minute
    assert_time_instant "Thursday 9 am (BST)", [2013, 2, 14, 6, 0, 0], :minute
  end

  # time_corpus.rs:2904
  def test_time_thursday_8_pst
    assert_time_instant "Thursday 8:00 PST", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday 8:00 pst", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday 8h00 PST", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday 8h00 pst", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday 8h PST", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday 8h pst", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thu at 8 am PST", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thu at 8 am pst", [2013, 2, 14, 14, 0, 0], :minute
    assert_time_instant "Thursday at 9:30pm ist", [2013, 2, 14, 14, 0, 0], :minute
  end

  # time_corpus.rs:3009
  def test_time_in_15_minutes
    assert_time_instant "in 15 minutes", [2013, 2, 12, 4, 45, 0], :second
    assert_time_instant "in 15'", [2013, 2, 12, 4, 45, 0], :second
    assert_time_instant "in 15", [2013, 2, 12, 4, 45, 0], :second
  end
end
