# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeIntervalWithContextTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:5102
  def test_weekend_inside_saturday_this
    assert_time_interval "this weekend", [2013, 2, 8, 18, 0, 0], [2013, 2, 11, 0, 0, 0], :hour, context: "saturday"
  end

  # time_corpus.rs:5115
  def test_weekend_inside_saturday_next
    assert_time_interval "next weekend", [2013, 2, 15, 18, 0, 0], [2013, 2, 18, 0, 0, 0], :hour, context: "saturday"
  end

  # time_corpus.rs:5128
  def test_weekend_inside_saturday_last
    assert_time_interval "last weekend", [2013, 2, 1, 18, 0, 0], [2013, 2, 4, 0, 0, 0], :hour, context: "saturday"
  end

  # time_corpus.rs:5141
  def test_weekend_inside_friday_evening_this
    assert_time_interval "this weekend", [2013, 2, 8, 18, 0, 0], [2013, 2, 11, 0, 0, 0], :hour, context: "friday_evening"
  end

  # time_corpus.rs:5154
  def test_weekend_inside_friday_evening_next
    assert_time_interval "next weekend", [2013, 2, 15, 18, 0, 0], [2013, 2, 18, 0, 0, 0], :hour, context: "friday_evening"
  end
end
