# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeIntervalTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:1441
  def test_time_interval_10_days_from_18th_dec
    assert_time_interval "for 10 days from 18th Dec", [2013, 12, 18, 0, 0, 0], [2013, 12, 29, 0, 0, 0], :day
    assert_time_interval "from 18th Dec for 10 days", [2013, 12, 18, 0, 0, 0], [2013, 12, 29, 0, 0, 0], :day
    assert_time_interval "18th Dec for 10 days", [2013, 12, 18, 0, 0, 0], [2013, 12, 29, 0, 0, 0], :day
  end

  # time_corpus.rs:1463
  def test_time_interval_30_min_from_4pm
    assert_time_interval "for 30' starting from 4pm", [2013, 2, 12, 16, 0, 0], [2013, 2, 12, 16, 31, 0], :minute
    assert_time_interval "from 4pm for thirty minutes", [2013, 2, 12, 16, 0, 0], [2013, 2, 12, 16, 31, 0], :minute
    assert_time_interval "4pm for 30 mins", [2013, 2, 12, 16, 0, 0], [2013, 2, 12, 16, 31, 0], :minute
    assert_time_interval "16h for 30 mins", [2013, 2, 12, 16, 0, 0], [2013, 2, 12, 16, 31, 0], :minute
  end

  # time_corpus.rs:1491
  def test_time_this_summer
    assert_time_interval "this Summer", [2013, 6, 21, 0, 0, 0], [2013, 9, 24, 0, 0, 0], :day
    assert_time_interval "current summer", [2013, 6, 21, 0, 0, 0], [2013, 9, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:1507
  def test_time_this_winter
    assert_time_interval "this winter", [2012, 12, 21, 0, 0, 0], [2013, 3, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:1517
  def test_time_this_season
    assert_time_interval "this season", [2012, 12, 21, 0, 0, 0], [2013, 3, 19, 0, 0, 0], :day
    assert_time_interval "current seasons", [2012, 12, 21, 0, 0, 0], [2013, 3, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:1533
  def test_time_last_season
    assert_time_interval "last season", [2012, 9, 23, 0, 0, 0], [2012, 12, 20, 0, 0, 0], :day
    assert_time_interval "past seasons", [2012, 9, 23, 0, 0, 0], [2012, 12, 20, 0, 0, 0], :day
    assert_time_interval "previous seasons", [2012, 9, 23, 0, 0, 0], [2012, 12, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:1555
  def test_time_next_season
    assert_time_interval "next season", [2013, 3, 20, 0, 0, 0], [2013, 6, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:1565
  def test_time_last_night
    assert_time_interval "last night", [2013, 2, 11, 18, 0, 0], [2013, 2, 12, 0, 0, 0], :hour
    assert_time_interval "yesterday evening", [2013, 2, 11, 18, 0, 0], [2013, 2, 12, 0, 0, 0], :hour
  end

  # time_corpus.rs:1581
  def test_time_late_last_night
    assert_time_interval "late last night", [2013, 2, 11, 21, 0, 0], [2013, 2, 12, 0, 0, 0], :hour
  end

  # time_corpus.rs:1603
  def test_time_morning_of_xmas
    assert_time_interval "morning of xmas", [2013, 12, 25, 0, 0, 0], [2013, 12, 25, 12, 0, 0], :hour
    assert_time_interval "morning of christmas 2013", [2013, 12, 25, 0, 0, 0], [2013, 12, 25, 12, 0, 0], :hour
    assert_time_interval "morning of this christmas day", [2013, 12, 25, 0, 0, 0], [2013, 12, 25, 12, 0, 0], :hour
  end

  # time_corpus.rs:1808
  def test_time_lent_2018
    assert_time_interval "lent 2018", [2018, 2, 14, 0, 0, 0], [2018, 4, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:1848
  def test_time_great_fast_2018
    assert_time_interval "great fast 2018", [2018, 2, 19, 0, 0, 0], [2018, 3, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:1858
  def test_time_this_evening
    assert_time_interval "this evening", [2013, 2, 12, 18, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "today evening", [2013, 2, 12, 18, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "tonight", [2013, 2, 12, 18, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
  end

  # time_corpus.rs:1880
  def test_time_this_past_weekend
    assert_time_interval "this past weekend", [2013, 2, 8, 18, 0, 0], [2013, 2, 11, 0, 0, 0], :hour
  end

  # time_corpus.rs:1890
  def test_time_tomorrow_evening
    assert_time_interval "tomorrow evening", [2013, 2, 13, 18, 0, 0], [2013, 2, 14, 0, 0, 0], :hour
  end

  # time_corpus.rs:1900
  def test_time_tomorrow_lunch
    assert_time_interval "tomorrow lunch", [2013, 2, 13, 12, 0, 0], [2013, 2, 13, 14, 0, 0], :hour
    assert_time_interval "tomorrow at lunch", [2013, 2, 13, 12, 0, 0], [2013, 2, 13, 14, 0, 0], :hour
  end

  # time_corpus.rs:1916
  def test_time_yesterday_evening
    assert_time_interval "yesterday evening", [2013, 2, 11, 18, 0, 0], [2013, 2, 12, 0, 0, 0], :hour
  end

  # time_corpus.rs:1926
  def test_time_this_weekend
    assert_time_interval "this week-end", [2013, 2, 15, 18, 0, 0], [2013, 2, 18, 0, 0, 0], :hour
  end

  # time_corpus.rs:1936
  def test_time_monday_morning
    assert_time_interval "monday mOrnIng", [2013, 2, 18, 0, 0, 0], [2013, 2, 18, 12, 0, 0], :hour
  end

  # time_corpus.rs:1946
  def test_time_monday_early_morning
    assert_time_interval "monday early in the morning", [2013, 2, 18, 0, 0, 0], [2013, 2, 18, 9, 0, 0], :hour
    assert_time_interval "monday early morning", [2013, 2, 18, 0, 0, 0], [2013, 2, 18, 9, 0, 0], :hour
    assert_time_interval "monday in the early hours of the morning", [2013, 2, 18, 0, 0, 0], [2013, 2, 18, 9, 0, 0], :hour
  end

  # time_corpus.rs:1968
  def test_time_late_tonight
    assert_time_interval "late tonight", [2013, 2, 12, 21, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "late tonite", [2013, 2, 12, 21, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
  end

  # time_corpus.rs:1984
  def test_time_february_15th_morning
    assert_time_interval "february the 15th in the morning", [2013, 2, 15, 0, 0, 0], [2013, 2, 15, 12, 0, 0], :hour
    assert_time_interval "15 of february in the morning", [2013, 2, 15, 0, 0, 0], [2013, 2, 15, 12, 0, 0], :hour
    assert_time_interval "morning of the 15th of february", [2013, 2, 15, 0, 0, 0], [2013, 2, 15, 12, 0, 0], :hour
  end

  # time_corpus.rs:2006
  def test_time_last_2_seconds
    assert_time_interval "last 2 seconds", [2013, 2, 12, 4, 29, 58], [2013, 2, 12, 4, 30, 0], :second
    assert_time_interval "last two seconds", [2013, 2, 12, 4, 29, 58], [2013, 2, 12, 4, 30, 0], :second
  end

  # time_corpus.rs:2022
  def test_time_next_3_seconds
    assert_time_interval "next 3 seconds", [2013, 2, 12, 4, 30, 1], [2013, 2, 12, 4, 30, 4], :second
    assert_time_interval "next three seconds", [2013, 2, 12, 4, 30, 1], [2013, 2, 12, 4, 30, 4], :second
  end

  # time_corpus.rs:2038
  def test_time_last_2_minutes
    assert_time_interval "last 2 minutes", [2013, 2, 12, 4, 28, 0], [2013, 2, 12, 4, 30, 0], :minute
    assert_time_interval "last two minutes", [2013, 2, 12, 4, 28, 0], [2013, 2, 12, 4, 30, 0], :minute
  end

  # time_corpus.rs:2054
  def test_time_next_3_minutes
    assert_time_interval "next 3 minutes", [2013, 2, 12, 4, 31, 0], [2013, 2, 12, 4, 34, 0], :minute
    assert_time_interval "next three minutes", [2013, 2, 12, 4, 31, 0], [2013, 2, 12, 4, 34, 0], :minute
  end

  # time_corpus.rs:2070
  def test_time_last_1_hour
    assert_time_interval "last 1 hour", [2013, 2, 12, 3, 0, 0], [2013, 2, 12, 4, 0, 0], :hour
    assert_time_interval "last one hour", [2013, 2, 12, 3, 0, 0], [2013, 2, 12, 4, 0, 0], :hour
  end

  # time_corpus.rs:2086
  def test_time_next_3_hours
    assert_time_interval "next 3 hours", [2013, 2, 12, 5, 0, 0], [2013, 2, 12, 8, 0, 0], :hour
    assert_time_interval "next three hours", [2013, 2, 12, 5, 0, 0], [2013, 2, 12, 8, 0, 0], :hour
  end

  # time_corpus.rs:2102
  def test_time_last_2_days
    assert_time_interval "last 2 days", [2013, 2, 10, 0, 0, 0], [2013, 2, 12, 0, 0, 0], :day
    assert_time_interval "last two days", [2013, 2, 10, 0, 0, 0], [2013, 2, 12, 0, 0, 0], :day
    assert_time_interval "past 2 days", [2013, 2, 10, 0, 0, 0], [2013, 2, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:2124
  def test_time_next_3_days
    assert_time_interval "next 3 days", [2013, 2, 13, 0, 0, 0], [2013, 2, 16, 0, 0, 0], :day
    assert_time_interval "next three days", [2013, 2, 13, 0, 0, 0], [2013, 2, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:2140
  def test_time_next_few_days
    assert_time_interval "next few days", [2013, 2, 13, 0, 0, 0], [2013, 2, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:2150
  def test_time_last_2_weeks
    assert_time_interval "last 2 weeks", [2013, 1, 28, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :week
    assert_time_interval "last two weeks", [2013, 1, 28, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :week
    assert_time_interval "past 2 weeks", [2013, 1, 28, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :week
  end

  # time_corpus.rs:2172
  def test_time_next_3_weeks
    assert_time_interval "next 3 weeks", [2013, 2, 18, 0, 0, 0], [2013, 3, 11, 0, 0, 0], :week
    assert_time_interval "next three weeks", [2013, 2, 18, 0, 0, 0], [2013, 3, 11, 0, 0, 0], :week
  end

  # time_corpus.rs:2188
  def test_time_last_2_months
    assert_time_interval "last 2 months", [2012, 12, 1, 0, 0, 0], [2013, 2, 1, 0, 0, 0], :month
    assert_time_interval "last two months", [2012, 12, 1, 0, 0, 0], [2013, 2, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:2204
  def test_time_next_3_months
    assert_time_interval "next 3 months", [2013, 3, 1, 0, 0, 0], [2013, 6, 1, 0, 0, 0], :month
    assert_time_interval "next three months", [2013, 3, 1, 0, 0, 0], [2013, 6, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:2220
  def test_time_last_2_years
    assert_time_interval "last 2 years", [2011, 1, 1, 0, 0, 0], [2013, 1, 1, 0, 0, 0], :year
    assert_time_interval "last two years", [2011, 1, 1, 0, 0, 0], [2013, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:2236
  def test_time_next_3_years
    assert_time_interval "next 3 years", [2014, 1, 1, 0, 0, 0], [2017, 1, 1, 0, 0, 0], :year
    assert_time_interval "next three years", [2014, 1, 1, 0, 0, 0], [2017, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:2252
  def test_time_july_13_to_15
    assert_time_interval "July 13-15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "July 13 to 15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "July 13 thru 15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "July 13 through 15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "July 13 - July 15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:2286
  def test_time_from_july_13_to_15
    assert_time_interval "from July 13-15", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13 to 15 July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13th to 15th July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13 to 15 July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13th to 15th July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13th to the 15th July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13 to the 15 July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:2332
  def test_time_from_13_to_15_of_july
    assert_time_interval "from 13 to 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13th to 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13 to 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13th to 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13 to the 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13th to the 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13 to the 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from 13th to the 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13 to the 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13th to the 15 of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13 to the 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
    assert_time_interval "from the 13th to the 15th of July", [2013, 7, 13, 0, 0, 0], [2013, 7, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:2408
  def test_time_aug_8_to_12
    assert_time_interval "Aug 8 - Aug 12", [2013, 8, 8, 0, 0, 0], [2013, 8, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:2418
  def test_time_930_to_1100
    assert_time_interval "9:30 - 11:00", [2013, 2, 12, 9, 30, 0], [2013, 2, 12, 11, 1, 0], :minute
    assert_time_interval "9h30 - 11h00", [2013, 2, 12, 9, 30, 0], [2013, 2, 12, 11, 1, 0], :minute
    assert_time_interval "9h30 - 11h", [2013, 2, 12, 9, 30, 0], [2013, 2, 12, 11, 1, 0], :minute
  end

  # time_corpus.rs:2440
  def test_time_930_to_1100_cst
    assert_time_interval "9:30 - 11:00 CST", [2013, 2, 12, 13, 30, 0], [2013, 2, 12, 15, 1, 0], :minute
    assert_time_interval "9h30 - 11h00 CST", [2013, 2, 12, 13, 30, 0], [2013, 2, 12, 15, 1, 0], :minute
    assert_time_interval "9h30 - 11h CST", [2013, 2, 12, 13, 30, 0], [2013, 2, 12, 15, 1, 0], :minute
  end

  # time_corpus.rs:2462
  def test_time_1500_gmt_to_1800_gmt
    assert_time_interval "15:00 GMT - 18:00 GMT", [2013, 2, 12, 13, 0, 0], [2013, 2, 12, 16, 1, 0], :minute
    assert_time_interval "15h00 GMT - 18h00 GMT", [2013, 2, 12, 13, 0, 0], [2013, 2, 12, 16, 1, 0], :minute
    assert_time_interval "15h GMT - 18h GMT", [2013, 2, 12, 13, 0, 0], [2013, 2, 12, 16, 1, 0], :minute
  end

  # time_corpus.rs:2484
  def test_time_iso8601_interval
    assert_time_interval "2015-03-28 17:00:00/2015-03-29 21:00:00", [2015, 3, 28, 17, 0, 0], [2015, 3, 29, 21, 0, 1], :second
  end

  # time_corpus.rs:2494
  def test_time_930_to_1100_on_thursday
    assert_time_interval "from 9:30 - 11:00 on Thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "between 9:30 and 11:00 on thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "between 9h30 and 11h00 on thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "9:30 - 11:00 on Thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "9h30 - 11h00 on Thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "later than 9:30 but before 11:00 on Thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "Thursday from 9:30 to 11:00", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "from 9:30 untill 11:00 on thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "Thursday from 9:30 untill 11:00", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
    assert_time_interval "9:30 till 11:00 on Thursday", [2013, 2, 14, 9, 30, 0], [2013, 2, 14, 11, 1, 0], :minute
  end

  # time_corpus.rs:2558
  def test_time_tomorrow_between_1_and_230
    assert_time_interval "tomorrow in between 1-2:30 ish", [2013, 2, 13, 1, 0, 0], [2013, 2, 13, 2, 31, 0], :minute
  end

  # time_corpus.rs:2568
  def test_time_3_to_4_pm
    assert_time_interval "3-4pm", [2013, 2, 12, 15, 0, 0], [2013, 2, 12, 17, 0, 0], :hour
    assert_time_interval "from 3 to 4 in the PM", [2013, 2, 12, 15, 0, 0], [2013, 2, 12, 17, 0, 0], :hour
    assert_time_interval "around 3-4pm", [2013, 2, 12, 15, 0, 0], [2013, 2, 12, 17, 0, 0], :hour
  end

  # time_corpus.rs:2590
  def test_time_330_to_6_pm
    assert_time_interval "3:30 to 6 PM", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "3:30-6 p.m.", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "3:30-6:00pm", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "15h30-18h", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "from 3:30 to six p.m.", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "from 3:30 to 6:00pm", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "later than 3:30pm but before 6pm", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
    assert_time_interval "between 3:30pm and 6 pm", [2013, 2, 12, 15, 30, 0], [2013, 2, 12, 18, 1, 0], :minute
  end

  # time_corpus.rs:2642
  def test_time_3pm_to_6pm_second_grain
    assert_time_interval "3pm - 6:00:00pm", [2013, 2, 12, 15, 0, 0], [2013, 2, 12, 18, 0, 1], :second
  end

  # time_corpus.rs:2652
  def test_time_8am_to_1pm
    assert_time_interval "8am - 1pm", [2013, 2, 12, 8, 0, 0], [2013, 2, 12, 14, 0, 0], :hour
  end

  # time_corpus.rs:2662
  def test_time_thursday_9a_to_11a
    assert_time_interval "Thursday from 9a to 11a", [2013, 2, 14, 9, 0, 0], [2013, 2, 14, 12, 0, 0], :hour
    assert_time_interval "this Thu 9-11am", [2013, 2, 14, 9, 0, 0], [2013, 2, 14, 12, 0, 0], :hour
  end

  # time_corpus.rs:2678
  def test_time_1130_to_130
    assert_time_interval "11:30-1:30", [2013, 2, 12, 11, 30, 0], [2013, 2, 12, 13, 31, 0], :minute
  end

  # time_corpus.rs:2697
  def test_time_within_2_weeks
    assert_time_interval "Within 2 weeks", [2013, 2, 12, 4, 30, 0], [2013, 2, 26, 0, 0, 0], :second
  end

  # time_corpus.rs:2707
  def test_time_by_2pm
    assert_time_interval "by 2:00pm", [2013, 2, 12, 4, 30, 0], [2013, 2, 12, 14, 0, 0], :second
  end

  # time_corpus.rs:2717
  def test_time_eod
    assert_time_interval "EOD", [2013, 2, 12, 17, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "end of day", [2013, 2, 12, 17, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "end of the day", [2013, 2, 12, 17, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
    assert_time_interval "the end of the day", [2013, 2, 12, 17, 0, 0], [2013, 2, 13, 0, 0, 0], :hour
  end

  # time_corpus.rs:2745
  def test_time_by_eod
    assert_time_interval "by EOD", [2013, 2, 12, 4, 30, 0], [2013, 2, 13, 0, 0, 0], :second
    assert_time_interval "by end of day", [2013, 2, 12, 4, 30, 0], [2013, 2, 13, 0, 0, 0], :second
    assert_time_interval "by the end of the day", [2013, 2, 12, 4, 30, 0], [2013, 2, 13, 0, 0, 0], :second
  end

  # time_corpus.rs:2767
  def test_time_by_eom
    assert_time_interval "by EOM", [2013, 2, 12, 4, 30, 0], [2013, 3, 1, 0, 0, 0], :second
    assert_time_interval "by the EOM", [2013, 2, 12, 4, 30, 0], [2013, 3, 1, 0, 0, 0], :second
    assert_time_interval "by end of the month", [2013, 2, 12, 4, 30, 0], [2013, 3, 1, 0, 0, 0], :second
    assert_time_interval "by the end of month", [2013, 2, 12, 4, 30, 0], [2013, 3, 1, 0, 0, 0], :second
  end

  # time_corpus.rs:2795
  def test_time_eom
    assert_time_interval "EOM", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
    assert_time_interval "the EOM", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
    assert_time_interval "at the EOM", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
    assert_time_interval "the end of the month", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
    assert_time_interval "end of the month", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
    assert_time_interval "at the end of month", [2013, 2, 21, 0, 0, 0], [2013, 3, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:2835
  def test_time_bom
    assert_time_interval "BOM", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "the BOM", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "at the BOM", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "beginning of the month", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "the beginning of the month", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "at the beginning of month", [2013, 2, 1, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:2875
  def test_time_by_end_of_next_month
    assert_time_interval "by the end of next month", [2013, 2, 12, 4, 30, 0], [2013, 4, 1, 0, 0, 0], :second
  end

  # time_corpus.rs:2981
  def test_time_in_the_afternoon
    assert_time_interval "in the afternoon", [2013, 2, 12, 12, 0, 0], [2013, 2, 12, 19, 0, 0], :hour
  end

  # time_corpus.rs:2991
  def test_time_8am_until_6
    assert_time_interval "8am until 6", [2013, 2, 12, 8, 0, 0], [2013, 2, 12, 19, 0, 0], :hour
  end

  # time_corpus.rs:3016
  def test_time_after_lunch
    assert_time_interval "after lunch", [2013, 2, 12, 13, 0, 0], [2013, 2, 12, 17, 0, 0], :hour
  end

  # time_corpus.rs:3026
  def test_time_after_school
    assert_time_interval "after school", [2013, 2, 12, 15, 0, 0], [2013, 2, 12, 21, 0, 0], :hour
  end

  # time_corpus.rs:3042
  def test_time_this_morning
    assert_time_interval "this morning", [2013, 2, 12, 0, 0, 0], [2013, 2, 12, 12, 0, 0], :hour
  end

  # time_corpus.rs:3287
  def test_time_tomorrow_afternoon
    assert_time_interval "tomorrow afternoon", [2013, 2, 13, 12, 0, 0], [2013, 2, 13, 19, 0, 0], :hour
    assert_time_interval "tomorrow afternoonish", [2013, 2, 13, 12, 0, 0], [2013, 2, 13, 19, 0, 0], :hour
  end

  # time_corpus.rs:3303
  def test_time_1pm_to_2pm_tomorrow
    assert_time_interval "1pm-2pm tomorrow", [2013, 2, 13, 13, 0, 0], [2013, 2, 13, 15, 0, 0], :hour
  end

  # time_corpus.rs:3374
  def test_time_early_march
    assert_time_interval "early March", [2013, 3, 1, 0, 0, 0], [2013, 3, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:3384
  def test_time_mid_march
    assert_time_interval "mid March", [2013, 3, 11, 0, 0, 0], [2013, 3, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:3394
  def test_time_late_march
    assert_time_interval "late March", [2013, 3, 21, 0, 0, 0], [2013, 4, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:3404
  def test_time_last_weekend_of_october
    assert_time_interval "last weekend of October", [2013, 10, 25, 18, 0, 0], [2013, 10, 28, 0, 0, 0], :hour
    assert_time_interval "last week-end in October", [2013, 10, 25, 18, 0, 0], [2013, 10, 28, 0, 0, 0], :hour
    assert_time_interval "last week end of October", [2013, 10, 25, 18, 0, 0], [2013, 10, 28, 0, 0, 0], :hour
  end

  # time_corpus.rs:3426
  def test_time_all_week
    assert_time_interval "all week", [2013, 2, 11, 0, 0, 0], [2013, 2, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:3436
  def test_time_rest_of_the_week
    assert_time_interval "rest of the week", [2013, 2, 12, 0, 0, 0], [2013, 2, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:3446
  def test_time_last_weekend_of_july
    assert_time_interval "last wkend of July", [2013, 7, 26, 18, 0, 0], [2013, 7, 29, 0, 0, 0], :hour
  end

  # time_corpus.rs:3456
  def test_time_last_weekend_of_october_2017
    assert_time_interval "last weekend of October 2017", [2017, 10, 27, 18, 0, 0], [2017, 10, 30, 0, 0, 0], :hour
  end

  # time_corpus.rs:3466
  def test_time_august_27th_to_29th
    assert_time_interval "August 27th - 29th", [2013, 8, 27, 0, 0, 0], [2013, 8, 30, 0, 0, 0], :day
    assert_time_interval "from August 27th - 29th", [2013, 8, 27, 0, 0, 0], [2013, 8, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:3482
  def test_time_23rd_to_26th_oct
    assert_time_interval "23rd to 26th Oct", [2013, 10, 23, 0, 0, 0], [2013, 10, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:3492
  def test_time_1_to_8_september
    assert_time_interval "1-8 september", [2013, 9, 1, 0, 0, 0], [2013, 9, 9, 0, 0, 0], :day
  end

  # time_corpus.rs:3502
  def test_time_12_to_16_september
    assert_time_interval "12 to 16 september", [2013, 9, 12, 0, 0, 0], [2013, 9, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:3512
  def test_time_19th_to_21st_aug
    assert_time_interval "19th To 21st aug", [2013, 8, 19, 0, 0, 0], [2013, 8, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:3522
  def test_time_end_of_april
    assert_time_interval "end of April", [2013, 4, 21, 0, 0, 0], [2013, 5, 1, 0, 0, 0], :day
    assert_time_interval "at the end of April", [2013, 4, 21, 0, 0, 0], [2013, 5, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:3538
  def test_time_beginning_of_january
    assert_time_interval "beginning of January", [2014, 1, 1, 0, 0, 0], [2014, 1, 11, 0, 0, 0], :day
    assert_time_interval "at the beginning of January", [2014, 1, 1, 0, 0, 0], [2014, 1, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:3554
  def test_time_end_of_2012
    assert_time_interval "end of 2012", [2012, 9, 1, 0, 0, 0], [2013, 1, 1, 0, 0, 0], :month
    assert_time_interval "at the end of 2012", [2012, 9, 1, 0, 0, 0], [2013, 1, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:3570
  def test_time_beginning_of_2017
    assert_time_interval "beginning of 2017", [2017, 1, 1, 0, 0, 0], [2017, 4, 1, 0, 0, 0], :month
    assert_time_interval "at the beginning of 2017", [2017, 1, 1, 0, 0, 0], [2017, 4, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:3586
  def test_time_beginning_of_year
    assert_time_interval "beginning of year", [2013, 1, 1, 0, 0, 0], [2013, 4, 1, 0, 0, 0], :month
    assert_time_interval "the beginning of the year", [2013, 1, 1, 0, 0, 0], [2013, 4, 1, 0, 0, 0], :month
    assert_time_interval "the BOY", [2013, 1, 1, 0, 0, 0], [2013, 4, 1, 0, 0, 0], :month
    assert_time_interval "BOY", [2013, 1, 1, 0, 0, 0], [2013, 4, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:3614
  def test_time_by_eoy
    assert_time_interval "by EOY", [2013, 2, 12, 4, 30, 0], [2014, 1, 1, 0, 0, 0], :second
    assert_time_interval "by the EOY", [2013, 2, 12, 4, 30, 0], [2014, 1, 1, 0, 0, 0], :second
    assert_time_interval "by end of the year", [2013, 2, 12, 4, 30, 0], [2014, 1, 1, 0, 0, 0], :second
    assert_time_interval "by the end of year", [2013, 2, 12, 4, 30, 0], [2014, 1, 1, 0, 0, 0], :second
  end

  # time_corpus.rs:3642
  def test_time_eoy
    assert_time_interval "EOY", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
    assert_time_interval "the EOY", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
    assert_time_interval "at the EOY", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
    assert_time_interval "the end of the year", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
    assert_time_interval "end of the year", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
    assert_time_interval "at the end of year", [2013, 9, 1, 0, 0, 0], [2014, 1, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:3682
  def test_time_beginning_of_this_week
    assert_time_interval "beginning of this week", [2013, 2, 11, 0, 0, 0], [2013, 2, 14, 0, 0, 0], :day
    assert_time_interval "beginning of current week", [2013, 2, 11, 0, 0, 0], [2013, 2, 14, 0, 0, 0], :day
    assert_time_interval "at the beginning of this week", [2013, 2, 11, 0, 0, 0], [2013, 2, 14, 0, 0, 0], :day
    assert_time_interval "at the beginning of current week", [2013, 2, 11, 0, 0, 0], [2013, 2, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:3710
  def test_time_beginning_of_coming_week
    assert_time_interval "beginning of coming week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "at the beginning of coming week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:3726
  def test_time_beginning_of_last_week
    assert_time_interval "beginning of last week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
    assert_time_interval "beginning of past week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
    assert_time_interval "beginning of previous week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
    assert_time_interval "at the beginning of last week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
    assert_time_interval "at the beginning of past week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
    assert_time_interval "at the beginning of previous week", [2013, 2, 4, 0, 0, 0], [2013, 2, 7, 0, 0, 0], :day
  end

  # time_corpus.rs:3766
  def test_time_beginning_of_next_week
    assert_time_interval "beginning of next week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "beginning of the following week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "beginning of around next week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "at the beginning of next week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "at the beginning of the following week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
    assert_time_interval "at the beginning of around next week", [2013, 2, 18, 0, 0, 0], [2013, 2, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:3806
  def test_time_end_of_this_week
    assert_time_interval "end of this week", [2013, 2, 15, 0, 0, 0], [2013, 2, 18, 0, 0, 0], :day
    assert_time_interval "end of current week", [2013, 2, 15, 0, 0, 0], [2013, 2, 18, 0, 0, 0], :day
    assert_time_interval "at the end of this week", [2013, 2, 15, 0, 0, 0], [2013, 2, 18, 0, 0, 0], :day
    assert_time_interval "at the end of current week", [2013, 2, 15, 0, 0, 0], [2013, 2, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:3834
  def test_time_end_of_coming_week
    assert_time_interval "end of coming week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "at the end of coming week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:3850
  def test_time_end_of_last_week
    assert_time_interval "end of last week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "end of past week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "end of previous week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "at the end of last week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "at the end of past week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
    assert_time_interval "at the end of previous week", [2013, 2, 8, 0, 0, 0], [2013, 2, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:3890
  def test_time_end_of_next_week
    assert_time_interval "end of next week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "end of the following week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "end of around next week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "at the end of next week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "at the end of the following week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
    assert_time_interval "at the end of around next week", [2013, 2, 22, 0, 0, 0], [2013, 2, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4000
  def test_rosh_hashanah_2018
    assert_time_interval "rosh hashanah 2018", [2018, 9, 9, 0, 0, 0], [2018, 9, 12, 0, 0, 0], :day
    assert_time_interval "rosh hashana 2018", [2018, 9, 9, 0, 0, 0], [2018, 9, 12, 0, 0, 0], :day
    assert_time_interval "rosh hashanna 2018", [2018, 9, 9, 0, 0, 0], [2018, 9, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:4022
  def test_chanukah_2018
    assert_time_interval "Chanukah 2018", [2018, 12, 2, 0, 0, 0], [2018, 12, 10, 0, 0, 0], :day
    assert_time_interval "hanukah 2018", [2018, 12, 2, 0, 0, 0], [2018, 12, 10, 0, 0, 0], :day
    assert_time_interval "hannukkah 2018", [2018, 12, 2, 0, 0, 0], [2018, 12, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:4044
  def test_passover_2018
    assert_time_interval "passover 2018", [2018, 3, 30, 0, 0, 0], [2018, 4, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:4054
  def test_sukkot_2018
    assert_time_interval "feast of the ingathering 2018", [2018, 9, 23, 0, 0, 0], [2018, 10, 2, 0, 0, 0], :day
    assert_time_interval "succos 2018", [2018, 9, 23, 0, 0, 0], [2018, 10, 2, 0, 0, 0], :day
  end

  # time_corpus.rs:4070
  def test_shavuot_2018
    assert_time_interval "shavuot 2018", [2018, 5, 19, 0, 0, 0], [2018, 5, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:4208
  def test_ramadan_1950
    assert_time_interval "Ramadan 1950", [1950, 6, 17, 0, 0, 0], [1950, 7, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:4218
  def test_ramadan_1977
    assert_time_interval "Ramadan 1977", [1977, 8, 15, 0, 0, 0], [1977, 9, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4228
  def test_ramadan_2018
    assert_time_interval "Ramadan 2018", [2018, 5, 16, 0, 0, 0], [2018, 6, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:4238
  def test_ramadan_2034
    assert_time_interval "Ramadan 2034", [2034, 11, 12, 0, 0, 0], [2034, 12, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:4248
  def test_ramadan_2046
    assert_time_interval "Ramadan 2046", [2046, 7, 5, 0, 0, 0], [2046, 8, 4, 0, 0, 0], :day
  end

  # time_corpus.rs:4258
  def test_ramadan_2050
    assert_time_interval "Ramadan 2050", [2050, 5, 22, 0, 0, 0], [2050, 6, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:4326
  def test_navaratri_2018
    assert_time_interval "navaratri 2018", [2018, 10, 9, 0, 0, 0], [2018, 10, 19, 0, 0, 0], :day
    assert_time_interval "durga puja in 2018", [2018, 10, 9, 0, 0, 0], [2018, 10, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:4459
  def test_gysd_2013
    assert_time_interval "GYSD 2013", [2013, 4, 26, 0, 0, 0], [2013, 4, 29, 0, 0, 0], :day
    assert_time_interval "global youth service day", [2013, 4, 26, 0, 0, 0], [2013, 4, 29, 0, 0, 0], :day
  end

  # time_corpus.rs:4483
  def test_earth_hour
    assert_time_interval "earth hour", [2013, 3, 23, 20, 30, 0], [2013, 3, 23, 21, 31, 0], :minute
  end

  # time_corpus.rs:4493
  def test_earth_hour_2016
    assert_time_interval "earth hour 2016", [2016, 3, 19, 20, 30, 0], [2016, 3, 19, 21, 31, 0], :minute
  end

  # time_corpus.rs:5167
  def test_weekend_outside_tuesday_this
    assert_time_interval "this weekend", [2013, 2, 15, 18, 0, 0], [2013, 2, 18, 0, 0, 0], :hour
  end

  # time_corpus.rs:5178
  def test_weekend_outside_tuesday_last
    assert_time_interval "last weekend", [2013, 2, 8, 18, 0, 0], [2013, 2, 11, 0, 0, 0], :hour
  end
end
