# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeNaiveTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:230
  def test_time_today
    assert_time_naive "today", [2013, 2, 12, 0, 0, 0], :day
    assert_time_naive "at this time", [2013, 2, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:239
  def test_time_month_year_slash
    assert_time_naive "2/2013", [2013, 2, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:247
  def test_time_in_2014
    assert_time_naive "in 2014", [2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:255
  def test_time_yesterday
    assert_time_naive "yesterday", [2013, 2, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:263
  def test_time_tomorrow
    assert_time_naive "tomorrow", [2013, 2, 13, 0, 0, 0], :day
    assert_time_naive "tomorrows", [2013, 2, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:272
  def test_time_monday
    assert_time_naive "monday", [2013, 2, 18, 0, 0, 0], :day
    assert_time_naive "mon.", [2013, 2, 18, 0, 0, 0], :day
    assert_time_naive "this monday", [2013, 2, 18, 0, 0, 0], :day
    assert_time_naive "Monday, Feb 18", [2013, 2, 18, 0, 0, 0], :day
    assert_time_naive "Mon, February 18", [2013, 2, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:284
  def test_time_tuesday
    assert_time_naive "tuesday", [2013, 2, 19, 0, 0, 0], :day
    assert_time_naive "Tuesday the 19th", [2013, 2, 19, 0, 0, 0], :day
    assert_time_naive "Tuesday 19th", [2013, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:294
  def test_time_thu_15th
    assert_time_naive "Thu 15th", [2013, 8, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:302
  def test_time_thursday
    assert_time_naive "thursday", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "thu", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "thu.", [2013, 2, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:312
  def test_time_friday
    assert_time_naive "friday", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "fri", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "fri.", [2013, 2, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:322
  def test_time_saturday
    assert_time_naive "saturday", [2013, 2, 16, 0, 0, 0], :day
    assert_time_naive "sat", [2013, 2, 16, 0, 0, 0], :day
    assert_time_naive "sat.", [2013, 2, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:332
  def test_time_sunday
    assert_time_naive "sunday", [2013, 2, 17, 0, 0, 0], :day
    assert_time_naive "sun", [2013, 2, 17, 0, 0, 0], :day
    assert_time_naive "sun.", [2013, 2, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:342
  def test_time_first_of_march
    assert_time_naive "the 1st of march", [2013, 3, 1, 0, 0, 0], :day
    assert_time_naive "first of march", [2013, 3, 1, 0, 0, 0], :day
    assert_time_naive "the first of march", [2013, 3, 1, 0, 0, 0], :day
    assert_time_naive "march first", [2013, 3, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:353
  def test_time_second_of_march
    assert_time_naive "the 2nd of march", [2013, 3, 2, 0, 0, 0], :day
    assert_time_naive "second of march", [2013, 3, 2, 0, 0, 0], :day
    assert_time_naive "the second of march", [2013, 3, 2, 0, 0, 0], :day
  end

  # time_corpus.rs:363
  def test_time_march_3
    assert_time_naive "march 3", [2013, 3, 3, 0, 0, 0], :day
    assert_time_naive "the third of march", [2013, 3, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:372
  def test_time_ides_of_march
    assert_time_naive "the ides of march", [2013, 3, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:380
  def test_time_march_3_2015
    assert_time_naive "march 3 2015", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "march 3rd 2015", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "march third 2015", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "3/3/2015", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "3/3/15", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "2015-3-3", [2015, 3, 3, 0, 0, 0], :day
    assert_time_naive "2015-03-03", [2015, 3, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:394
  def test_time_february_15
    assert_time_naive "on the 15th", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "the 15th of february", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "15 of february", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "february the 15th", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "february 15", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "15th february", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "February 15", [2013, 2, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:408
  def test_time_aug_8
    assert_time_naive "Aug 8", [2013, 8, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:416
  def test_time_march_in_a_year
    assert_time_naive "March in 1 year", [2014, 3, 1, 0, 0, 0], :month
    assert_time_naive "March in a year", [2014, 3, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:425
  def test_time_fri_jul_18
    assert_time_naive "Fri, Jul 18", [2014, 7, 18, 0, 0, 0], :day
    assert_time_naive "Jul 18, Fri", [2014, 7, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:434
  def test_time_october_2014
    assert_time_naive "October 2014", [2014, 10, 1, 0, 0, 0], :month
    assert_time_naive "2014-10", [2014, 10, 1, 0, 0, 0], :month
    assert_time_naive "2014/10", [2014, 10, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:444
  def test_time_april_14_2015
    assert_time_naive "14april 2015", [2015, 4, 14, 0, 0, 0], :day
    assert_time_naive "April 14, 2015", [2015, 4, 14, 0, 0, 0], :day
    assert_time_naive "14th April 15", [2015, 4, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:454
  def test_time_next_tuesday
    assert_time_naive "next tuesday", [2013, 2, 19, 0, 0, 0], :day
    assert_time_naive "around next tuesday", [2013, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:463
  def test_time_friday_after_next
    assert_time_naive "friday after next", [2013, 2, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:471
  def test_time_next_march
    assert_time_naive "next March", [2013, 3, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:479
  def test_time_march_after_next
    assert_time_naive "March after next", [2014, 3, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:487
  def test_time_sunday_feb_10
    assert_time_naive "Sunday, Feb 10", [2013, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:495
  def test_time_wed_feb13
    assert_time_naive "Wed, Feb13", [2013, 2, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:503
  def test_time_this_week
    assert_time_naive "this week", [2013, 2, 11, 0, 0, 0], :week
    assert_time_naive "current week", [2013, 2, 11, 0, 0, 0], :week
  end

  # time_corpus.rs:512
  def test_time_last_week
    assert_time_naive "last week", [2013, 2, 4, 0, 0, 0], :week
    assert_time_naive "past week", [2013, 2, 4, 0, 0, 0], :week
    assert_time_naive "previous week", [2013, 2, 4, 0, 0, 0], :week
  end

  # time_corpus.rs:522
  def test_time_next_week
    assert_time_naive "next week", [2013, 2, 18, 0, 0, 0], :week
    assert_time_naive "the following week", [2013, 2, 18, 0, 0, 0], :week
    assert_time_naive "around next week", [2013, 2, 18, 0, 0, 0], :week
    assert_time_naive "upcoming week", [2013, 2, 18, 0, 0, 0], :week
    assert_time_naive "coming week", [2013, 2, 18, 0, 0, 0], :week
  end

  # time_corpus.rs:534
  def test_time_last_month
    assert_time_naive "last month", [2013, 1, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:542
  def test_time_next_month
    assert_time_naive "next month", [2013, 3, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:550
  def test_time_20_of_next_month
    assert_time_naive "20 of next month", [2013, 3, 20, 0, 0, 0], :day
    assert_time_naive "20th of the next month", [2013, 3, 20, 0, 0, 0], :day
    assert_time_naive "20th day of next month", [2013, 3, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:560
  def test_time_20_of_current_month
    assert_time_naive "20th of the current month", [2013, 2, 20, 0, 0, 0], :day
    assert_time_naive "20 of this month", [2013, 2, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:569
  def test_time_20_of_previous_month
    assert_time_naive "20th of the previous month", [2013, 1, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:581
  def test_time_this_quarter
    assert_time_naive "this quarter", [2013, 1, 1, 0, 0, 0], :quarter
    assert_time_naive "this qtr", [2013, 1, 1, 0, 0, 0], :quarter
  end

  # time_corpus.rs:590
  def test_time_next_quarter
    assert_time_naive "next quarter", [2013, 4, 1, 0, 0, 0], :quarter
    assert_time_naive "next qtr", [2013, 4, 1, 0, 0, 0], :quarter
  end

  # time_corpus.rs:599
  def test_time_third_quarter
    assert_time_naive "third quarter", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "3rd quarter", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "third qtr", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "3rd qtr", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "the 3rd qtr", [2013, 7, 1, 0, 0, 0], :quarter
  end

  # time_corpus.rs:611
  def test_time_4th_quarter_2018
    assert_time_naive "4th quarter 2018", [2018, 10, 1, 0, 0, 0], :quarter
    assert_time_naive "4th qtr 2018", [2018, 10, 1, 0, 0, 0], :quarter
    assert_time_naive "the 4th qtr of 2018", [2018, 10, 1, 0, 0, 0], :quarter
    assert_time_naive "18q4", [2018, 10, 1, 0, 0, 0], :quarter
    assert_time_naive "2018Q4", [2018, 10, 1, 0, 0, 0], :quarter
  end

  # time_corpus.rs:623
  def test_time_last_year
    assert_time_naive "last year", [2012, 1, 1, 0, 0, 0], :year
    assert_time_naive "last yr", [2012, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:632
  def test_time_this_year
    assert_time_naive "this year", [2013, 1, 1, 0, 0, 0], :year
    assert_time_naive "current year", [2013, 1, 1, 0, 0, 0], :year
    assert_time_naive "this yr", [2013, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:642
  def test_time_next_year
    assert_time_naive "next year", [2014, 1, 1, 0, 0, 0], :year
    assert_time_naive "next yr", [2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:651
  def test_time_in_2014_ad
    assert_time_naive "in 2014 A.D.", [2014, 1, 1, 0, 0, 0], :year
    assert_time_naive "in 2014 AD", [2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:660
  def test_time_in_2014_bc
    assert_time_naive "in 2014 B.C.", [-2014, 1, 1, 0, 0, 0], :year
    assert_time_naive "in 2014 BC", [-2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:669
  def test_time_in_14_ad
    assert_time_naive "in 14 a.d.", [14, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:677
  def test_time_last_sunday
    assert_time_naive "last sunday", [2013, 2, 10, 0, 0, 0], :day
    assert_time_naive "sunday from last week", [2013, 2, 10, 0, 0, 0], :day
    assert_time_naive "last week's sunday", [2013, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:687
  def test_time_last_tuesday
    assert_time_naive "last tuesday", [2013, 2, 5, 0, 0, 0], :day
  end

  # time_corpus.rs:695
  def test_time_next_wednesday
    assert_time_naive "next wednesday", [2013, 2, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:703
  def test_time_wednesday_of_next_week
    assert_time_naive "wednesday of next week", [2013, 2, 20, 0, 0, 0], :day
    assert_time_naive "wednesday next week", [2013, 2, 20, 0, 0, 0], :day
    assert_time_naive "wednesday after next", [2013, 2, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:713
  def test_time_monday_of_this_week
    assert_time_naive "monday of this week", [2013, 2, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:721
  def test_time_tuesday_of_this_week
    assert_time_naive "tuesday of this week", [2013, 2, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:729
  def test_time_wednesday_of_this_week
    assert_time_naive "wednesday of this week", [2013, 2, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:737
  def test_time_day_after_tomorrow
    assert_time_naive "the day after tomorrow", [2013, 2, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:745
  def test_time_day_after_tomorrow_5pm
    assert_time_naive "day after tomorrow 5pm", [2013, 2, 14, 17, 0, 0], :hour
  end

  # time_corpus.rs:753
  def test_time_day_before_yesterday
    assert_time_naive "the day before yesterday", [2013, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:761
  def test_time_day_before_yesterday_8am
    assert_time_naive "day before yesterday 8am", [2013, 2, 10, 8, 0, 0], :hour
  end

  # time_corpus.rs:769
  def test_time_last_monday_of_march
    assert_time_naive "last Monday of March", [2013, 3, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:777
  def test_time_last_sunday_of_march_2014
    assert_time_naive "last Sunday of March 2014", [2014, 3, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:785
  def test_time_third_day_of_october
    assert_time_naive "third day of october", [2013, 10, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:793
  def test_time_first_week_of_october_2014
    assert_time_naive "first week of october 2014", [2014, 10, 6, 0, 0, 0], :week
  end

  # time_corpus.rs:805
  def test_time_third_last_week_of_2018
    assert_time_naive "third last week of 2018", [2018, 12, 10, 0, 0, 0], :week
    assert_time_naive "the third last week of 2018", [2018, 12, 10, 0, 0, 0], :week
    assert_time_naive "the 3rd last week of 2018", [2018, 12, 10, 0, 0, 0], :week
  end

  # time_corpus.rs:823
  def test_time_2nd_last_week_of_october_2018
    assert_time_naive "2nd last week of October 2018", [2018, 10, 15, 0, 0, 0], :week
    assert_time_naive "the second last week of October 2018", [2018, 10, 15, 0, 0, 0], :week
  end

  # time_corpus.rs:840
  def test_time_fifth_last_day_of_may
    assert_time_naive "fifth last day of May", [2013, 5, 27, 0, 0, 0], :day
    assert_time_naive "the 5th last day of May", [2013, 5, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:849
  def test_time_week_of_october
    assert_time_naive "the week of october 6th", [2013, 10, 7, 0, 0, 0], :week
    assert_time_naive "the week of october 7th", [2013, 10, 7, 0, 0, 0], :week
  end

  # time_corpus.rs:858
  def test_time_last_day_of_october_2015
    assert_time_naive "last day of october 2015", [2015, 10, 31, 0, 0, 0], :day
    assert_time_naive "last day in october 2015", [2015, 10, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:867
  def test_time_last_week_of_september_2014
    assert_time_naive "last week of september 2014", [2014, 9, 22, 0, 0, 0], :week
  end

  # time_corpus.rs:879
  def test_time_first_tuesday_of_october
    assert_time_naive "first tuesday of october", [2013, 10, 1, 0, 0, 0], :day
    assert_time_naive "first tuesday in october", [2013, 10, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:888
  def test_time_third_tuesday_of_september_2014
    assert_time_naive "third tuesday of september 2014", [2014, 9, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:900
  def test_time_first_wednesday_of_october_2014
    assert_time_naive "first wednesday of october 2014", [2014, 10, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:912
  def test_time_second_wednesday_of_october_2014
    assert_time_naive "second wednesday of october 2014", [2014, 10, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:924
  def test_time_third_tuesday_after_christmas_2014
    assert_time_naive "third tuesday after christmas 2014", [2015, 1, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:936
  def test_time_at_3am
    assert_time_naive "at 3am", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "3 in the AM", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "at 3 AM", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "3 oclock am", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "at three am", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "this morning at 3", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "3 in the morning", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "at 3 in the morning", [2013, 2, 13, 3, 0, 0], :hour
    assert_time_naive "early morning @ 3", [2013, 2, 13, 3, 0, 0], :hour
  end

  # time_corpus.rs:949
  def test_time_this_morning_at_10
    assert_time_naive "this morning @ 10", [2013, 2, 12, 10, 0, 0], :hour
    assert_time_naive "this morning at 10am", [2013, 2, 12, 10, 0, 0], :hour
  end

  # time_corpus.rs:955
  def test_time_3_18am
    assert_time_naive "3:18am", [2013, 2, 13, 3, 18, 0], :minute
    assert_time_naive "3:18a", [2013, 2, 13, 3, 18, 0], :minute
    assert_time_naive "3h18", [2013, 2, 13, 3, 18, 0], :minute
  end

  # time_corpus.rs:962
  def test_time_at_7_in_3_years
    assert_time_naive "at 7 in 3 years", [2016, 2, 1, 7, 0, 0], :hour
  end

  # time_corpus.rs:967
  def test_time_at_3pm
    assert_time_naive "at 3pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "@ 3pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3PM", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3 oclock pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3 o'clock in the afternoon", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3ish pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "3pm approximately", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "at about 3pm", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "at 3p", [2013, 2, 12, 15, 0, 0], :hour
    assert_time_naive "at 3p.", [2013, 2, 12, 15, 0, 0], :hour
  end

  # time_corpus.rs:986
  def test_time_15h00
    assert_time_naive "15h00", [2013, 2, 12, 15, 0, 0], :minute
    assert_time_naive "at 15h00", [2013, 2, 12, 15, 0, 0], :minute
    assert_time_naive "15h", [2013, 2, 12, 15, 0, 0], :minute
    assert_time_naive "at 15h", [2013, 2, 12, 15, 0, 0], :minute
  end

  # time_corpus.rs:994
  def test_time_quarter_past_3pm
    assert_time_naive "at 15 past 3pm", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "a quarter past 3pm", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "for a quarter past 3pm", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "3:15 in the afternoon", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "15:15", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "15h15", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "3:15pm", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "3:15PM", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "3:15p", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "at 3 15", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "15 minutes past 3pm", [2013, 2, 12, 15, 15, 0], :minute
    assert_time_naive "15 minutes past 15h", [2013, 2, 12, 15, 15, 0], :minute
  end

  # time_corpus.rs:1018
  def test_time_20_past_3pm
    assert_time_naive "at 20 past 3pm", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "3:20 in the afternoon", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "3:20 in afternoon", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "twenty after 3pm", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "3:20p", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "15h20", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "at three twenty", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "20 minutes past 3pm", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "this afternoon at 3:20", [2013, 2, 12, 15, 20, 0], :minute
    assert_time_naive "tonight @ 3:20", [2013, 2, 12, 15, 20, 0], :minute
  end

  # time_corpus.rs:1040
  def test_time_half_past_3pm
    assert_time_naive "at half past three pm", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "half past 3 pm", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "15:30", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "15h30", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "3:30pm", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "3:30PM", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "330 p.m.", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "3:30 p m", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "3:30", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "half three", [2013, 2, 12, 15, 30, 0], :minute
    assert_time_naive "30 minutes past 3 pm", [2013, 2, 12, 15, 30, 0], :minute
  end

  # time_corpus.rs:1059
  def test_time_quarter_past_noon
    assert_time_naive "at 15 past noon", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "a quarter past noon", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "for a quarter past noon", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12:15 in the afternoon", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12:15", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12h15", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12:15pm", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12:15PM", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "12:15p", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "at 12 15", [2013, 2, 12, 12, 15, 0], :minute
    assert_time_naive "15 minutes past noon", [2013, 2, 12, 12, 15, 0], :minute
  end

  # time_corpus.rs:1082
  def test_time_nine_fifty_nine_am
    assert_time_naive "nine fifty nine a m", [2013, 2, 12, 9, 59, 0], :minute
  end

  # time_corpus.rs:1087
  def test_time_15_23_24
    assert_time_naive "15:23:24", [2013, 2, 12, 15, 23, 24], :second
  end

  # time_corpus.rs:1092
  def test_time_9_01_10_am
    assert_time_naive "9:01:10 AM", [2013, 2, 12, 9, 1, 10], :second
  end

  # time_corpus.rs:1097
  def test_time_quarter_to_noon
    assert_time_naive "a quarter to noon", [2013, 2, 12, 11, 45, 0], :minute
    assert_time_naive "11:45am", [2013, 2, 12, 11, 45, 0], :minute
    assert_time_naive "11h45", [2013, 2, 12, 11, 45, 0], :minute
    assert_time_naive "15 to noon", [2013, 2, 12, 11, 45, 0], :minute
  end

  # time_corpus.rs:1105
  def test_time_quarter_past_1pm
    assert_time_naive "a quarter past 1pm", [2013, 2, 12, 13, 15, 0], :minute
    assert_time_naive "for a quarter past 1pm", [2013, 2, 12, 13, 15, 0], :minute
    assert_time_naive "1:15pm", [2013, 2, 12, 13, 15, 0], :minute
    assert_time_naive "13h15", [2013, 2, 12, 13, 15, 0], :minute
    assert_time_naive "15 minutes from 1pm", [2013, 2, 12, 13, 15, 0], :minute
  end

  # time_corpus.rs:1118
  def test_time_quarter_past_2pm
    assert_time_naive "a quarter past 2pm", [2013, 2, 12, 14, 15, 0], :minute
    assert_time_naive "for a quarter past 2pm", [2013, 2, 12, 14, 15, 0], :minute
  end

  # time_corpus.rs:1128
  def test_time_quarter_past_8pm
    assert_time_naive "a quarter past 8pm", [2013, 2, 12, 20, 15, 0], :minute
    assert_time_naive "for a quarter past 8pm", [2013, 2, 12, 20, 15, 0], :minute
  end

  # time_corpus.rs:1138
  def test_time_8_tonight
    assert_time_naive "8 tonight", [2013, 2, 12, 20, 0, 0], :hour
    assert_time_naive "tonight at 8 o'clock", [2013, 2, 12, 20, 0, 0], :hour
    assert_time_naive "eight tonight", [2013, 2, 12, 20, 0, 0], :hour
    assert_time_naive "8 this evening", [2013, 2, 12, 20, 0, 0], :hour
    assert_time_naive "at 8 in the evening", [2013, 2, 12, 20, 0, 0], :hour
    assert_time_naive "in the evening at eight", [2013, 2, 12, 20, 0, 0], :hour
  end

  # time_corpus.rs:1148
  def test_time_7_30pm_fri_sep_20
    assert_time_naive "at 7:30 PM on Fri, Sep 20", [2013, 9, 20, 19, 30, 0], :minute
    assert_time_naive "at 19h30 on Fri, Sep 20", [2013, 9, 20, 19, 30, 0], :minute
  end

  # time_corpus.rs:1162
  def test_time_saturday_at_9am
    assert_time_naive "at 9am on Saturday", [2013, 2, 16, 9, 0, 0], :hour
    assert_time_naive "Saturday morning at 9", [2013, 2, 16, 9, 0, 0], :hour
    assert_time_naive "on Saturday for 9am", [2013, 2, 16, 9, 0, 0], :hour
  end

  # time_corpus.rs:1169
  def test_time_fri_jul_18_2014_7pm
    assert_time_naive "Fri, Jul 18, 2014 07:00 PM", [2014, 7, 18, 19, 0, 0], :minute
    assert_time_naive "Fri, Jul 18, 2014 19h00", [2014, 7, 18, 19, 0, 0], :minute
    assert_time_naive "Fri, Jul 18, 2014 19h", [2014, 7, 18, 19, 0, 0], :minute
  end

  # time_corpus.rs:1294
  def test_time_3_years_from_today
    assert_time_naive "3 years from today", [2016, 2, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:1299
  def test_time_3_fridays_from_now
    assert_time_naive "3 fridays from now", [2013, 3, 1, 0, 0, 0], :day
    assert_time_naive "three fridays from now", [2013, 3, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:1305
  def test_time_2_sundays_from_now
    assert_time_naive "2 sundays from now", [2013, 2, 24, 0, 0, 0], :day
    assert_time_naive "two sundays from now", [2013, 2, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:1311
  def test_time_4_tuesdays_from_now
    assert_time_naive "4 tuesdays from now", [2013, 3, 12, 0, 0, 0], :day
    assert_time_naive "four tuesdays from now", [2013, 3, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:1361
  def test_time_2_thursdays_ago
    assert_time_naive "2 thursdays back", [2013, 1, 31, 0, 0, 0], :day
    assert_time_naive "2 thursdays ago", [2013, 1, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:1377
  def test_time_first_monday_of_this_month
    assert_time_naive "the first Monday of this month", [2013, 2, 4, 0, 0, 0], :day
    assert_time_naive "the first Monday of the month", [2013, 2, 4, 0, 0, 0], :day
    assert_time_naive "the first Monday in this month", [2013, 2, 4, 0, 0, 0], :day
    assert_time_naive "first Monday in the month", [2013, 2, 4, 0, 0, 0], :day
  end

  # time_corpus.rs:1435
  def test_time_one_year_after_christmas
    assert_time_naive "one year After christmas", [2013, 12, 25, 0, 0, 0], :day
    assert_time_naive "a year from Christmas", [2013, 12, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:1591
  def test_time_christmas
    assert_time_naive "xmas", [2013, 12, 25, 0, 0, 0], :day
    assert_time_naive "christmas", [2013, 12, 25, 0, 0, 0], :day
    assert_time_naive "christmas day", [2013, 12, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:1598
  def test_time_xmas_at_6pm
    assert_time_naive "xmas at 6 pm", [2013, 12, 25, 18, 0, 0], :hour
  end

  # time_corpus.rs:1625
  def test_time_new_years_eve
    assert_time_naive "new year's eve", [2013, 12, 31, 0, 0, 0], :day
    assert_time_naive "new years eve", [2013, 12, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:1631
  def test_time_new_years_day
    assert_time_naive "new year's day", [2014, 1, 1, 0, 0, 0], :day
    assert_time_naive "new years day", [2014, 1, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:1637
  def test_time_valentines_day
    assert_time_naive "valentine's day", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "valentine day", [2013, 2, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:1643
  def test_time_4th_of_july
    assert_time_naive "4th of July", [2013, 7, 4, 0, 0, 0], :day
    assert_time_naive "4 of july", [2013, 7, 4, 0, 0, 0], :day
  end

  # time_corpus.rs:1649
  def test_time_halloween
    assert_time_naive "halloween", [2013, 10, 31, 0, 0, 0], :day
    assert_time_naive "next halloween", [2013, 10, 31, 0, 0, 0], :day
    assert_time_naive "Halloween 2013", [2013, 10, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:1656
  def test_time_black_friday
    assert_time_naive "black friday", [2013, 11, 29, 0, 0, 0], :day
    assert_time_naive "black friday of this year", [2013, 11, 29, 0, 0, 0], :day
    assert_time_naive "black friday 2013", [2013, 11, 29, 0, 0, 0], :day
  end

  # time_corpus.rs:1667
  def test_time_black_friday_2017
    assert_time_naive "black friday 2017", [2017, 11, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:1672
  def test_time_boss_day
    assert_time_naive "boss's day", [2013, 10, 16, 0, 0, 0], :day
    assert_time_naive "boss's", [2013, 10, 16, 0, 0, 0], :day
    assert_time_naive "boss day", [2013, 10, 16, 0, 0, 0], :day
    assert_time_naive "next boss's day", [2013, 10, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:1680
  def test_time_boss_day_2016
    assert_time_naive "boss's day 2016", [2016, 10, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:1685
  def test_time_boss_day_2021
    assert_time_naive "boss's day 2021", [2021, 10, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:1690
  def test_time_mlk_day
    assert_time_naive "MLK day", [2014, 1, 20, 0, 0, 0], :day
    assert_time_naive "next Martin Luther King day", [2014, 1, 20, 0, 0, 0], :day
    assert_time_naive "next Martin Luther King's day", [2014, 1, 20, 0, 0, 0], :day
    assert_time_naive "next Martin Luther Kings day", [2014, 1, 20, 0, 0, 0], :day
    assert_time_naive "this MLK day", [2014, 1, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:1711
  def test_time_last_mlk_day
    assert_time_naive "last MLK Jr. day", [2013, 1, 21, 0, 0, 0], :day
    assert_time_naive "MLK day 2013", [2013, 1, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:1717
  def test_time_mlk_day_last_year
    assert_time_naive "MLK day of last year", [2012, 1, 16, 0, 0, 0], :day
    assert_time_naive "MLK day 2012", [2012, 1, 16, 0, 0, 0], :day
    assert_time_naive "Civil Rights Day of last year", [2012, 1, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:1728
  def test_time_world_vegan_day
    assert_time_naive "world vegan day", [2013, 11, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:1733
  def test_time_easter
    assert_time_naive "easter", [2013, 3, 31, 0, 0, 0], :day
    assert_time_naive "easter 2013", [2013, 3, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:1739
  def test_time_last_easter
    assert_time_naive "last easter", [2012, 4, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:1744
  def test_time_easter_monday
    assert_time_naive "easter mon", [2013, 4, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:1749
  def test_time_easter_2010
    assert_time_naive "easter 2010", [2010, 4, 4, 0, 0, 0], :day
    assert_time_naive "Easter Sunday two thousand ten", [2010, 4, 4, 0, 0, 0], :day
  end

  # time_corpus.rs:1759
  def test_time_three_days_after_easter
    assert_time_naive "three days after Easter", [2013, 4, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:1764
  def test_time_maundy_thursday
    assert_time_naive "Maundy Thursday", [2013, 3, 28, 0, 0, 0], :day
    assert_time_naive "Covenant thu", [2013, 3, 28, 0, 0, 0], :day
    assert_time_naive "Thu of Mysteries", [2013, 3, 28, 0, 0, 0], :day
  end

  # time_corpus.rs:1771
  def test_time_pentecost
    assert_time_naive "Pentecost", [2013, 5, 19, 0, 0, 0], :day
    assert_time_naive "white sunday 2013", [2013, 5, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:1777
  def test_time_whit_monday
    assert_time_naive "whit monday", [2013, 5, 20, 0, 0, 0], :day
    assert_time_naive "Monday of the Holy Spirit", [2013, 5, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:1783
  def test_time_palm_sunday
    assert_time_naive "palm sunday", [2013, 3, 24, 0, 0, 0], :day
    assert_time_naive "branch sunday 2013", [2013, 3, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:1789
  def test_time_trinity_sunday
    assert_time_naive "trinity sunday", [2013, 5, 26, 0, 0, 0], :day
  end

  # time_corpus.rs:1794
  def test_time_pancake_day
    assert_time_naive "pancake day 2013", [2013, 2, 12, 0, 0, 0], :day
    assert_time_naive "mardi gras", [2013, 2, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:1800
  def test_time_st_patricks_day
    assert_time_naive "st patrick's day 2013", [2013, 3, 17, 0, 0, 0], :day
    assert_time_naive "st paddy's day", [2013, 3, 17, 0, 0, 0], :day
    assert_time_naive "saint paddy's day", [2013, 3, 17, 0, 0, 0], :day
    assert_time_naive "saint patricks day", [2013, 3, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:1818
  def test_time_orthodox_easter_2018
    assert_time_naive "orthodox easter 2018", [2018, 4, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:1823
  def test_time_orthodox_good_friday_2020
    assert_time_naive "orthodox good friday 2020", [2020, 4, 17, 0, 0, 0], :day
    assert_time_naive "orthodox great friday 2020", [2020, 4, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:1833
  def test_time_clean_monday_2018
    assert_time_naive "clean monday 2018", [2018, 2, 19, 0, 0, 0], :day
    assert_time_naive "orthodox shrove monday two thousand eighteen", [2018, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:1843
  def test_time_lazarus_saturday_2018
    assert_time_naive "lazarus saturday 2018", [2018, 3, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:2688
  def test_time_130pm_sat_sep_21
    assert_time_naive "1:30 PM on Sat, Sep 21", [2013, 9, 21, 13, 30, 0], :minute
  end

  # time_corpus.rs:2921
  def test_time_today_at_2pm
    assert_time_naive "today at 2pm", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_naive "at 2pm", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_naive "this afternoon at 2", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_naive "this evening at 2", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_naive "tonight at 2", [2013, 2, 12, 14, 0, 0], :hour
  end

  # time_corpus.rs:2930
  def test_time_3pm_tomorrow
    assert_time_naive "3pm tomorrow", [2013, 2, 13, 15, 0, 0], :hour
  end

  # time_corpus.rs:2935
  def test_time_today_in_one_hour
    assert_time_naive "today in one hour", [2013, 2, 12, 5, 30, 0], :minute
  end

  # time_corpus.rs:3001
  def test_time_at_130pm
    assert_time_naive "at 1:30pm", [2013, 2, 12, 13, 30, 0], :minute
    assert_time_naive "1:30pm", [2013, 2, 12, 13, 30, 0], :minute
    assert_time_naive "at 13h30", [2013, 2, 12, 13, 30, 0], :minute
    assert_time_naive "13h30", [2013, 2, 12, 13, 30, 0], :minute
  end

  # time_corpus.rs:3036
  def test_time_1030
    assert_time_naive "10:30", [2013, 2, 12, 10, 30, 0], :minute
    assert_time_naive "approximately 1030", [2013, 2, 12, 10, 30, 0], :minute
  end

  # time_corpus.rs:3052
  def test_time_next_monday
    assert_time_naive "next monday", [2013, 2, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:3057
  def test_time_at_noon
    assert_time_naive "at 12pm", [2013, 2, 12, 12, 0, 0], :hour
    assert_time_naive "at noon", [2013, 2, 12, 12, 0, 0], :hour
    assert_time_naive "midday", [2013, 2, 12, 12, 0, 0], :hour
    assert_time_naive "the midday", [2013, 2, 12, 12, 0, 0], :hour
    assert_time_naive "mid day", [2013, 2, 12, 12, 0, 0], :hour
  end

  # time_corpus.rs:3066
  def test_time_at_midnight
    assert_time_naive "at 12am", [2013, 2, 13, 0, 0, 0], :hour
    assert_time_naive "at midnight", [2013, 2, 13, 0, 0, 0], :hour
    assert_time_naive "this morning at 12", [2013, 2, 13, 0, 0, 0], :hour
    assert_time_naive "this evening at 12", [2013, 2, 13, 0, 0, 0], :hour
    assert_time_naive "this afternoon at 12", [2013, 2, 13, 0, 0, 0], :hour
  end

  # time_corpus.rs:3075
  def test_time_9_tomorrow_morning
    assert_time_naive "9 tomorrow morning", [2013, 2, 13, 9, 0, 0], :hour
    assert_time_naive "9 tomorrow", [2013, 2, 13, 9, 0, 0], :hour
  end

  # time_corpus.rs:3081
  def test_time_9_tomorrow_evening
    assert_time_naive "9 tomorrow evening", [2013, 2, 13, 21, 0, 0], :hour
  end

  # time_corpus.rs:3086
  def test_time_march
    assert_time_naive "in March", [2013, 3, 1, 0, 0, 0], :month
    assert_time_naive "during March", [2013, 3, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:3107
  def test_may_and_march_as_months
    assert_time_naive "in May", [2013, 5, 1, 0, 0, 0], :month
    assert_time_naive "May 3rd", [2013, 5, 3, 0, 0, 0], :day
    assert_time_naive "last May", [2012, 5, 1, 0, 0, 0], :month
    assert_time_naive "next March", [2013, 3, 1, 0, 0, 0], :month
    assert_time_naive "March 15", [2013, 3, 15, 0, 0, 0], :day
    assert_time_naive "March 15, 2015", [2015, 3, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:3118
  def test_iso_datetime_no_spurious_interval
    assert_time_naive "2025-03-17 at 4.35.24 PM", [2025, 3, 17, 16, 35, 24], :second
  end

  # time_corpus.rs:3155
  def test_dot_separated_times
    assert_time_naive "4.35 PM", [2013, 2, 12, 16, 35, 0], :minute
    assert_time_naive "10.30", [2013, 2, 12, 10, 30, 0], :minute
    assert_time_naive "4.35.24 PM", [2013, 2, 12, 16, 35, 24], :second
  end

  # time_corpus.rs:3245
  def test_last_april_first_is_previous_occurrence
    assert_time_naive "last April 1", [2012, 4, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:3278
  def test_time_tomorrow_afternoon_at_5
    assert_time_naive "tomorrow afternoon at 5", [2013, 2, 13, 17, 0, 0], :hour
    assert_time_naive "at 5 tomorrow afternoon", [2013, 2, 13, 17, 0, 0], :hour
    assert_time_naive "at 5pm tomorrow", [2013, 2, 13, 17, 0, 0], :hour
    assert_time_naive "tomorrow at 5pm", [2013, 2, 13, 17, 0, 0], :hour
    assert_time_naive "tomorrow evening at 5", [2013, 2, 13, 17, 0, 0], :hour
  end

  # time_corpus.rs:3313
  def test_time_on_the_first
    assert_time_naive "on the first", [2013, 3, 1, 0, 0, 0], :day
    assert_time_naive "the 1st", [2013, 3, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:3319
  def test_time_at_1030_am
    assert_time_naive "at 1030", [2013, 2, 12, 10, 30, 0], :minute
    assert_time_naive "around 1030", [2013, 2, 12, 10, 30, 0], :minute
    assert_time_naive "ten thirty am", [2013, 2, 12, 10, 30, 0], :minute
  end

  # time_corpus.rs:3326
  def test_time_730_in_the_evening
    assert_time_naive "at 730 in the evening", [2013, 2, 12, 19, 30, 0], :minute
    assert_time_naive "seven thirty p.m.", [2013, 2, 12, 19, 30, 0], :minute
  end

  # time_corpus.rs:3336
  def test_time_tomorrow_at_150ish
    assert_time_naive "tomorrow at 150ish", [2013, 2, 13, 1, 50, 0], :minute
  end

  # time_corpus.rs:3341
  def test_time_tonight_at_11
    assert_time_naive "tonight at 11", [2013, 2, 12, 23, 0, 0], :hour
    assert_time_naive "this evening at 11", [2013, 2, 12, 23, 0, 0], :hour
    assert_time_naive "this afternoon at 11", [2013, 2, 12, 23, 0, 0], :hour
    assert_time_naive "tonight at 11pm", [2013, 2, 12, 23, 0, 0], :hour
  end

  # time_corpus.rs:3349
  def test_time_at_423
    assert_time_naive "at 4:23", [2013, 2, 12, 4, 23, 0], :minute
    assert_time_naive "4:23am", [2013, 2, 12, 4, 23, 0], :minute
    assert_time_naive "four twenty-three a m", [2013, 2, 12, 4, 23, 0], :minute
  end

  # time_corpus.rs:3356
  def test_time_closest_monday_to_oct_5th
    assert_time_naive "the closest Monday to Oct 5th", [2013, 10, 7, 0, 0, 0], :day
  end

  # time_corpus.rs:3365
  def test_time_second_closest_monday_to_oct_5th
    assert_time_naive "the second closest Mon to October fifth", [2013, 9, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:3934
  def test_chinese_new_year
    assert_time_naive "chinese new year", [2014, 1, 31, 0, 0, 0], :day
    assert_time_naive "chinese lunar new year's day", [2014, 1, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:3944
  def test_last_chinese_new_year
    assert_time_naive "last chinese new year", [2013, 2, 10, 0, 0, 0], :day
    assert_time_naive "last chinese lunar new year's day", [2013, 2, 10, 0, 0, 0], :day
    assert_time_naive "last chinese new years", [2013, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:3955
  def test_chinese_new_year_2018
    assert_time_naive "chinese new year's day 2018", [2018, 2, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:3964
  def test_yom_kippur_2018
    assert_time_naive "yom kippur 2018", [2018, 9, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:3969
  def test_shemini_atzeret_2018
    assert_time_naive "shemini atzeret 2018", [2018, 9, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:3974
  def test_simchat_torah_2018
    assert_time_naive "simchat torah 2018", [2018, 10, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:3979
  def test_tisha_bav_2018
    assert_time_naive "tisha b'av 2018", [2018, 7, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:3984
  def test_yom_haatzmaut_2018
    assert_time_naive "yom haatzmaut 2018", [2018, 4, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:3989
  def test_lag_bomer_2017
    assert_time_naive "lag b'omer 2017", [2017, 5, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:3994
  def test_yom_hashoah_2018
    assert_time_naive "Yom Hashoah 2018", [2018, 4, 11, 0, 0, 0], :day
    assert_time_naive "Holocaust Day 2018", [2018, 4, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:4080
  def test_mawlid_2017
    assert_time_naive "mawlid al-nabawi 2017", [2017, 11, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:4085
  def test_eid_al_fitr_1950
    assert_time_naive "Eid al-Fitr 1950", [1950, 7, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:4090
  def test_eid_al_fitr_1975
    assert_time_naive "Eid al-Fitr 1975", [1975, 10, 6, 0, 0, 0], :day
  end

  # time_corpus.rs:4095
  def test_eid_al_fitr_1988
    assert_time_naive "Eid al-Fitr 1988", [1988, 5, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:4100
  def test_eid_al_fitr_2018
    assert_time_naive "Eid al-Fitr 2018", [2018, 6, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:4105
  def test_eid_al_fitr_2034
    assert_time_naive "Eid al-Fitr 2034", [2034, 12, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:4110
  def test_eid_al_fitr_2046
    assert_time_naive "Eid al-Fitr 2046", [2046, 8, 4, 0, 0, 0], :day
  end

  # time_corpus.rs:4115
  def test_eid_al_fitr_2050
    assert_time_naive "Eid al-Fitr 2050", [2050, 6, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:4120
  def test_eid_al_adha_2018
    assert_time_naive "Eid al-Adha 2018", [2018, 8, 21, 0, 0, 0], :day
    assert_time_naive "id ul-adha 2018", [2018, 8, 21, 0, 0, 0], :day
    assert_time_naive "sacrifice feast 2018", [2018, 8, 21, 0, 0, 0], :day
    assert_time_naive "Bakr Id 2018", [2018, 8, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:4128
  def test_eid_al_adha_1980
    assert_time_naive "Eid al-Adha 1980", [1980, 10, 19, 0, 0, 0], :day
    assert_time_naive "id ul-adha 1980", [1980, 10, 19, 0, 0, 0], :day
    assert_time_naive "sacrifice feast 1980", [1980, 10, 19, 0, 0, 0], :day
    assert_time_naive "Bakr Id 1980", [1980, 10, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:4136
  def test_eid_al_adha_1966
    assert_time_naive "Eid al-Adha 1966", [1966, 4, 1, 0, 0, 0], :day
    assert_time_naive "id ul-adha 1966", [1966, 4, 1, 0, 0, 0], :day
    assert_time_naive "sacrifice feast 1966", [1966, 4, 1, 0, 0, 0], :day
    assert_time_naive "Bakr Id 1966", [1966, 4, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:4144
  def test_eid_al_adha_1974
    assert_time_naive "Eid al-Adha 1974", [1974, 1, 3, 0, 0, 0], :day
    assert_time_naive "id ul-adha 1974", [1974, 1, 3, 0, 0, 0], :day
    assert_time_naive "sacrifice feast 1974", [1974, 1, 3, 0, 0, 0], :day
    assert_time_naive "Bakr Id 1974", [1974, 1, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:4152
  def test_laylat_al_qadr_2017
    assert_time_naive "laylat al kadr 2017", [2017, 6, 22, 0, 0, 0], :day
    assert_time_naive "night of measures 2017", [2017, 6, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:4158
  def test_laylat_al_qadr_2018
    assert_time_naive "laylat al-qadr 2018", [2018, 6, 11, 0, 0, 0], :day
    assert_time_naive "night of power 2018", [2018, 6, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:4164
  def test_islamic_new_year_2018
    assert_time_naive "Islamic New Year 2018", [2018, 9, 11, 0, 0, 0], :day
    assert_time_naive "Amun Jadid 2018", [2018, 9, 11, 0, 0, 0], :day
  end

  # time_corpus.rs:4170
  def test_ashura_2017
    assert_time_naive "day of Ashura 2017", [2017, 9, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:4175
  def test_tu_bishvat_2018
    assert_time_naive "tu bishvat 2018", [2018, 1, 30, 0, 0, 0], :day
  end

  # time_corpus.rs:4180
  def test_jamat_ul_vida_2017
    assert_time_naive "Jamat Ul-Vida 2017", [2017, 6, 23, 0, 0, 0], :day
    assert_time_naive "Jumu'atul-Wida 2017", [2017, 6, 23, 0, 0, 0], :day
  end

  # time_corpus.rs:4186
  def test_jamat_ul_vida_2018
    assert_time_naive "Jamat Ul-Vida 2018", [2018, 6, 8, 0, 0, 0], :day
    assert_time_naive "Jumu'atul-Wida 2018", [2018, 6, 8, 0, 0, 0], :day
  end

  # time_corpus.rs:4192
  def test_isra_and_miraj_2018
    assert_time_naive "isra and mi'raj 2018", [2018, 4, 13, 0, 0, 0], :day
    assert_time_naive "the prophet's ascension 2018", [2018, 4, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:4202
  def test_night_journey_2019
    assert_time_naive "the night journey 2019", [2019, 4, 3, 0, 0, 0], :day
    assert_time_naive "ascension to heaven 2019", [2019, 4, 3, 0, 0, 0], :day
  end

  # time_corpus.rs:4268
  def test_dhanatrayodashi_2017
    assert_time_naive "dhanatrayodashi in 2017", [2017, 10, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:4273
  def test_dhanteras_2019
    assert_time_naive "dhanteras 2019", [2019, 10, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4278
  def test_kali_chaudas_2019
    assert_time_naive "kali chaudas 2019", [2019, 10, 26, 0, 0, 0], :day
    assert_time_naive "choti diwali two thousand nineteen", [2019, 10, 26, 0, 0, 0], :day
  end

  # time_corpus.rs:4288
  def test_diwali_2019
    assert_time_naive "diwali 2019", [2019, 10, 27, 0, 0, 0], :day
    assert_time_naive "Deepavali in 2019", [2019, 10, 27, 0, 0, 0], :day
    assert_time_naive "Lakshmi Puja six years hence", [2019, 10, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:4299
  def test_bhai_dooj_2019
    assert_time_naive "bhai dooj 2019", [2019, 10, 29, 0, 0, 0], :day
  end

  # time_corpus.rs:4304
  def test_chhath_2019
    assert_time_naive "chhath 2019", [2019, 11, 2, 0, 0, 0], :day
    assert_time_naive "dala puja 2019", [2019, 11, 2, 0, 0, 0], :day
    assert_time_naive "Surya Shashthi in 2019", [2019, 11, 2, 0, 0, 0], :day
  end

  # time_corpus.rs:4311
  def test_maha_saptami_2021
    assert_time_naive "Maha Saptami 2021", [2021, 10, 12, 0, 0, 0], :day
  end

  # time_corpus.rs:4316
  def test_dussehra_2018
    assert_time_naive "Dussehra 2018", [2018, 10, 18, 0, 0, 0], :day
    assert_time_naive "vijayadashami in five years", [2018, 10, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:4342
  def test_karva_chauth_2018
    assert_time_naive "karva chauth 2018", [2018, 10, 27, 0, 0, 0], :day
    assert_time_naive "karva chauth in 2018", [2018, 10, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:4348
  def test_ratha_yatra_2018
    assert_time_naive "ratha-yatra 2018", [2018, 7, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4353
  def test_rakhi_2018
    assert_time_naive "rakhi 2018", [2018, 8, 26, 0, 0, 0], :day
  end

  # time_corpus.rs:4358
  def test_mahavir_jayanti_2020
    assert_time_naive "mahavir jayanti 2020", [2020, 4, 6, 0, 0, 0], :day
    assert_time_naive "mahaveer janma kalyanak 2020", [2020, 4, 6, 0, 0, 0], :day
  end

  # time_corpus.rs:4368
  def test_maha_shivaratri_2020
    assert_time_naive "maha shivaratri 2020", [2020, 2, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:4373
  def test_saraswati_jayanti_2018
    assert_time_naive "saraswati jayanti 2018", [2018, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:4378
  def test_pongal_2018
    assert_time_naive "pongal 2018", [2018, 1, 14, 0, 0, 0], :day
    assert_time_naive "makara sankranthi 2018", [2018, 1, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4384
  def test_bogi_pandigai_2018
    assert_time_naive "bogi pandigai 2018", [2018, 1, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:4389
  def test_maattu_pongal_2018
    assert_time_naive "maattu pongal 2018", [2018, 1, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:4394
  def test_kaanum_pongal_2018
    assert_time_naive "kaanum pongal 2018", [2018, 1, 16, 0, 0, 0], :day
    assert_time_naive "kanni pongal 2018", [2018, 1, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:4400
  def test_makar_sankranti_2019
    assert_time_naive "makar sankranti 2019", [2019, 1, 15, 0, 0, 0], :day
    assert_time_naive "maghi in 2019", [2019, 1, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:4406
  def test_vaisakhi_2018
    assert_time_naive "Vaisakhi 2018", [2018, 4, 14, 0, 0, 0], :day
    assert_time_naive "baisakhi in 2018", [2018, 4, 14, 0, 0, 0], :day
    assert_time_naive "Vasakhi 2018", [2018, 4, 14, 0, 0, 0], :day
    assert_time_naive "vaishakhi 2018", [2018, 4, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4414
  def test_onam_2018
    assert_time_naive "onam 2018", [2018, 8, 24, 0, 0, 0], :day
    assert_time_naive "Thiru Onam 2018", [2018, 8, 24, 0, 0, 0], :day
    assert_time_naive "Thiruvonam 2018", [2018, 8, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:4421
  def test_vasant_panchami_2019
    assert_time_naive "vasant panchami in 2019", [2019, 2, 10, 0, 0, 0], :day
    assert_time_naive "basant panchami 2019", [2019, 2, 10, 0, 0, 0], :day
  end

  # time_corpus.rs:4427
  def test_chhoti_holi_2019
    assert_time_naive "chhoti holi 2019", [2019, 3, 20, 0, 0, 0], :day
    assert_time_naive "holika dahan 2019", [2019, 3, 20, 0, 0, 0], :day
    assert_time_naive "kamudu pyre 2019", [2019, 3, 20, 0, 0, 0], :day
  end

  # time_corpus.rs:4434
  def test_krishna_janmashtami_2019
    assert_time_naive "krishna janmashtami 2019", [2019, 8, 23, 0, 0, 0], :day
    assert_time_naive "gokulashtami 2019", [2019, 8, 23, 0, 0, 0], :day
  end

  # time_corpus.rs:4440
  def test_holi_2019
    assert_time_naive "holi 2019", [2019, 3, 21, 0, 0, 0], :day
    assert_time_naive "dhulandi 2019", [2019, 3, 21, 0, 0, 0], :day
    assert_time_naive "phagwah 2019", [2019, 3, 21, 0, 0, 0], :day
  end

  # time_corpus.rs:4447
  def test_parsi_new_year_2018
    assert_time_naive "Parsi New Year 2018", [2018, 8, 17, 0, 0, 0], :day
    assert_time_naive "Jamshedi Navroz 2018", [2018, 8, 17, 0, 0, 0], :day
  end

  # time_corpus.rs:4453
  def test_parsi_new_year_2022
    assert_time_naive "jamshedi Navroz 2022", [2022, 8, 16, 0, 0, 0], :day
    assert_time_naive "parsi new year 2022", [2022, 8, 16, 0, 0, 0], :day
  end

  # time_corpus.rs:4475
  def test_vesak
    assert_time_naive "vesak", [2013, 5, 24, 0, 0, 0], :day
    assert_time_naive "vaisakha", [2013, 5, 24, 0, 0, 0], :day
    assert_time_naive "Buddha day", [2013, 5, 24, 0, 0, 0], :day
    assert_time_naive "Buddha Purnima", [2013, 5, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:4503
  def test_purim
    assert_time_naive "purim", [2013, 2, 23, 0, 0, 0], :day
  end

  # time_corpus.rs:4508
  def test_shushan_purim
    assert_time_naive "Shushan Purim", [2013, 2, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:4513
  def test_guru_gobind_singh_jayanti
    assert_time_naive "guru gobind singh birthday", [2014, 1, 7, 0, 0, 0], :day
    assert_time_naive "guru gobind singh jayanti 2014", [2014, 1, 7, 0, 0, 0], :day
    assert_time_naive "guru gobind singh jayanti", [2014, 1, 7, 0, 0, 0], :day
    assert_time_naive "Guru Govind Singh Jayanti", [2014, 1, 7, 0, 0, 0], :day
  end

  # time_corpus.rs:4525
  def test_koningsdag_2018
    assert_time_naive "Koningsdag 2018", [2018, 4, 27, 0, 0, 0], :day
    assert_time_naive "koningsdag 2018", [2018, 4, 27, 0, 0, 0], :day
    assert_time_naive "king's day 2018", [2018, 4, 27, 0, 0, 0], :day
    assert_time_naive "King's Day 2018", [2018, 4, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:4533
  def test_koningsdag_2014
    assert_time_naive "Koningsdag 2014", [2014, 4, 26, 0, 0, 0], :day
    assert_time_naive "koningsdag 2014", [2014, 4, 26, 0, 0, 0], :day
    assert_time_naive "King's Day 2014", [2014, 4, 26, 0, 0, 0], :day
    assert_time_naive "king's day 2014", [2014, 4, 26, 0, 0, 0], :day
  end

  # time_corpus.rs:4541
  def test_rabindra_jayanti_2018
    assert_time_naive "rabindra jayanti 2018", [2018, 5, 9, 0, 0, 0], :day
    assert_time_naive "Rabindranath Jayanti 2018", [2018, 5, 9, 0, 0, 0], :day
    assert_time_naive "Rabindra Jayanti 2018", [2018, 5, 9, 0, 0, 0], :day
  end

  # time_corpus.rs:4548
  def test_rabindra_jayanti_2019
    assert_time_naive "rabindra jayanti 2019", [2019, 5, 9, 0, 0, 0], :day
    assert_time_naive "Rabindranath Jayanti 2019", [2019, 5, 9, 0, 0, 0], :day
    assert_time_naive "Rabindra Jayanti 2019", [2019, 5, 9, 0, 0, 0], :day
  end

  # time_corpus.rs:4555
  def test_guru_ravidas_jayanti_2018
    assert_time_naive "guru Ravidas jayanti 2018", [2018, 1, 31, 0, 0, 0], :day
    assert_time_naive "Guru Ravidass birthday 2018", [2018, 1, 31, 0, 0, 0], :day
    assert_time_naive "guru ravidass Jayanti 2018", [2018, 1, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:4570
  def test_guru_ravidas_jayanti_2019
    assert_time_naive "Guru Ravidass Jayanti 2019", [2019, 2, 19, 0, 0, 0], :day
    assert_time_naive "Guru Ravidas Birthday 2019", [2019, 2, 19, 0, 0, 0], :day
    assert_time_naive "guru ravidas jayanti 2019", [2019, 2, 19, 0, 0, 0], :day
  end

  # time_corpus.rs:4585
  def test_valmiki_jayanti_2019
    assert_time_naive "valmiki jayanti 2019", [2019, 10, 13, 0, 0, 0], :day
    assert_time_naive "Valmiki Jayanti 2019", [2019, 10, 13, 0, 0, 0], :day
    assert_time_naive "pargat diwas 2019", [2019, 10, 13, 0, 0, 0], :day
  end

  # time_corpus.rs:4592
  def test_valmiki_jayanti_2018
    assert_time_naive "maharishi valmiki jayanti 2018", [2018, 10, 24, 0, 0, 0], :day
    assert_time_naive "pargat diwas 2018", [2018, 10, 24, 0, 0, 0], :day
    assert_time_naive "Pargat Diwas 2018", [2018, 10, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:4603
  def test_ganesh_chaturthi_2019
    assert_time_naive "ganesh chaturthi 2019", [2019, 9, 2, 0, 0, 0], :day
  end

  # time_corpus.rs:4608
  def test_rama_navami_2020
    assert_time_naive "rama navami 2020", [2020, 4, 2, 0, 0, 0], :day
  end

  # time_corpus.rs:4613
  def test_ugadi_2018
    assert_time_naive "Ugadi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "ugadi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "yugadi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "Yugadi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "samvatsaradi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "chaitra sukladi 2018", [2018, 3, 18, 0, 0, 0], :day
    assert_time_naive "chaitra sukhladi 2018", [2018, 3, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:4624
  def test_closest_xmas
    assert_time_naive "the closest xmas to today", [2012, 12, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4633
  def test_second_closest_xmas
    assert_time_naive "the second closest xmas to today", [2013, 12, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4642
  def test_3rd_closest_xmas
    assert_time_naive "the 3rd closest xmas to today", [2011, 12, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4651
  def test_last_friday_of_october
    assert_time_naive "last friday of october", [2013, 10, 25, 0, 0, 0], :day
    assert_time_naive "last friday in october", [2013, 10, 25, 0, 0, 0], :day
  end

  # time_corpus.rs:4657
  def test_upcoming_two_weeks
    assert_time_naive "upcoming two weeks", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "upcoming two week", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "upcoming 2 weeks", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "upcoming 2 week", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "two upcoming weeks", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "two upcoming week", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "2 upcoming weeks", [2013, 2, 25, 0, 0, 0], :week
    assert_time_naive "2 upcoming week", [2013, 2, 25, 0, 0, 0], :week
  end

  # time_corpus.rs:4669
  def test_upcoming_two_days
    assert_time_naive "upcoming two days", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "upcoming two day", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "upcoming 2 days", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "upcoming 2 day", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "two upcoming days", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "two upcoming day", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "2 upcoming days", [2013, 2, 14, 0, 0, 0], :day
    assert_time_naive "2 upcoming day", [2013, 2, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4681
  def test_upcoming_two_months
    assert_time_naive "upcoming two months", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "upcoming two month", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "upcoming 2 months", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "upcoming 2 month", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "two upcoming months", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "two upcoming month", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "2 upcoming months", [2013, 4, 1, 0, 0, 0], :month
    assert_time_naive "2 upcoming month", [2013, 4, 1, 0, 0, 0], :month
  end

  # time_corpus.rs:4693
  def test_upcoming_two_quarters
    assert_time_naive "upcoming two quarters", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "upcoming two quarter", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "upcoming 2 quarters", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "upcoming 2 quarter", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "two upcoming quarters", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "two upcoming quarter", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "2 upcoming quarters", [2013, 7, 1, 0, 0, 0], :quarter
    assert_time_naive "2 upcoming quarter", [2013, 7, 1, 0, 0, 0], :quarter
  end

  # time_corpus.rs:4705
  def test_upcoming_two_years
    assert_time_naive "upcoming two years", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "upcoming two year", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "upcoming 2 years", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "upcoming 2 year", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "two upcoming years", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "two upcoming year", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "2 upcoming years", [2015, 1, 1, 0, 0, 0], :year
    assert_time_naive "2 upcoming year", [2015, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:4717
  def test_20_minutes_to_2pm_tomorrow
    assert_time_naive "20 minutes to 2pm tomorrow", [2013, 2, 13, 13, 40, 0], :minute
  end

  # time_corpus.rs:4726
  def test_first_monday_of_last_month
    assert_time_naive "first monday of last month", [2013, 1, 7, 0, 0, 0], :day
  end

  # time_corpus.rs:4731
  def test_first_tuesday_of_last_month
    assert_time_naive "first tuesday of last month", [2013, 1, 1, 0, 0, 0], :day
  end

  # time_corpus.rs:4740
  def test_second_monday_of_last_month
    assert_time_naive "second monday of last month", [2013, 1, 14, 0, 0, 0], :day
  end

  # time_corpus.rs:4749
  def test_next_saturday
    assert_time_naive "next saturday", [2013, 2, 23, 0, 0, 0], :day
  end

  # time_corpus.rs:4754
  def test_next_monday
    assert_time_naive "next monday", [2013, 2, 18, 0, 0, 0], :day
  end

  # time_corpus.rs:4763
  def test_us_date_format_2_15
    assert_time_naive "2/15", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "on 2/15", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "2 / 15", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "2-15", [2013, 2, 15, 0, 0, 0], :day
    assert_time_naive "2 - 15", [2013, 2, 15, 0, 0, 0], :day
  end

  # time_corpus.rs:4772
  def test_us_date_format_10_31_1974
    assert_time_naive "10/31/1974", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "10/31/74", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "10-31-74", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "10.31.1974", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "31/Oct/1974", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "31-Oct-74", [1974, 10, 31, 0, 0, 0], :day
    assert_time_naive "31st Oct 1974", [1974, 10, 31, 0, 0, 0], :day
  end

  # time_corpus.rs:4783
  def test_date_with_time_4_25
    assert_time_naive "4/25 at 4:00pm", [2013, 4, 25, 16, 0, 0], :minute
    assert_time_naive "4/25 at 16h00", [2013, 4, 25, 16, 0, 0], :minute
    assert_time_naive "4/25 at 16h", [2013, 4, 25, 16, 0, 0], :minute
  end

  # time_corpus.rs:4790
  def test_thanksgiving_2013
    assert_time_naive "thanksgiving day", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "thanksgiving", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "thanksgiving 2013", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "this thanksgiving", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "next thanksgiving day", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "thanksgiving in 9 months", [2013, 11, 28, 0, 0, 0], :day
    assert_time_naive "thanksgiving 9 months from now", [2013, 11, 28, 0, 0, 0], :day
  end

  # time_corpus.rs:4805
  def test_thanksgiving_next_year
    assert_time_naive "thanksgiving of next year", [2014, 11, 27, 0, 0, 0], :day
    assert_time_naive "thanksgiving in a year", [2014, 11, 27, 0, 0, 0], :day
    assert_time_naive "thanksgiving 2014", [2014, 11, 27, 0, 0, 0], :day
  end

  # time_corpus.rs:4816
  def test_last_thanksgiving
    assert_time_naive "last thanksgiving", [2012, 11, 22, 0, 0, 0], :day
    assert_time_naive "thanksgiving day 2012", [2012, 11, 22, 0, 0, 0], :day
    assert_time_naive "thanksgiving 3 months ago", [2012, 11, 22, 0, 0, 0], :day
    assert_time_naive "thanksgiving 1 year ago", [2012, 11, 22, 0, 0, 0], :day
  end

  # time_corpus.rs:4828
  def test_thanksgiving_2016
    assert_time_naive "thanksgiving 2016", [2016, 11, 24, 0, 0, 0], :day
    assert_time_naive "thanksgiving in 3 years", [2016, 11, 24, 0, 0, 0], :day
  end

  # time_corpus.rs:4834
  def test_thanksgiving_2017
    assert_time_naive "thanksgiving 2017", [2017, 11, 23, 0, 0, 0], :day
  end
end
