# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeNoTimeTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:4843
  def test_negative_laughing_out_loud
    assert_no_time "laughing out loud"
  end

  # time_corpus.rs:4848
  def test_negative_1_adult
    assert_no_time "1 adult"
  end

  # time_corpus.rs:4853
  def test_negative_we_are_separated
    assert_no_time "we are separated"
  end

  # time_corpus.rs:4858
  def test_negative_25
    assert_no_time "25"
  end

  # time_corpus.rs:4863
  def test_negative_this_is_the_one
    assert_no_time "this is the one"
  end

  # time_corpus.rs:4868
  def test_negative_this_one
    assert_no_time "this one"
  end

  # time_corpus.rs:4873
  def test_negative_this_past_one
    assert_no_time "this past one"
  end

  # time_corpus.rs:4878
  def test_negative_at_single
    assert_no_time "at single"
  end

  # time_corpus.rs:4883
  def test_negative_at_a_couple_of
    assert_no_time "at a couple of"
  end

  # time_corpus.rs:4888
  def test_negative_at_pairs
    assert_no_time "at pairs"
  end

  # time_corpus.rs:4893
  def test_negative_at_a_few
    assert_no_time "at a few"
  end

  # time_corpus.rs:4898
  def test_negative_at_dozens
    assert_no_time "at dozens"
  end

  # time_corpus.rs:4903
  def test_negative_single_oclock
    assert_no_time "single o'clock"
  end

  # time_corpus.rs:4908
  def test_negative_dozens_oclock
    assert_no_time "dozens o'clock"
  end

  # time_corpus.rs:4913
  def test_negative_rat_6
    assert_no_time "Rat 6"
    assert_no_time "rat 6"
  end

  # time_corpus.rs:4919
  def test_negative_3_30
    assert_no_time "3 30"
  end

  # time_corpus.rs:4924
  def test_negative_three_twenty
    assert_no_time "three twenty"
  end

  # time_corpus.rs:4929
  def test_negative_phone_number_dot
    assert_no_time "at 650.650.6500"
  end

  # time_corpus.rs:4934
  def test_negative_phone_number_dash
    assert_no_time "at 650-650-6500"
  end

  # time_corpus.rs:4939
  def test_negative_two_sixty_am
    assert_no_time "two sixty a m"
  end

  # time_corpus.rs:4944
  def test_negative_pay_abc_2000
    assert_no_time "Pay ABC 2000"
  end

  # time_corpus.rs:4949
  def test_negative_4a
    assert_no_time "4a"
  end

  # time_corpus.rs:4954
  def test_negative_4a_dot
    assert_no_time "4a."
  end

  # time_corpus.rs:4959
  def test_negative_a4_a5
    assert_no_time "A4 A5"
  end

  # time_corpus.rs:4964
  def test_negative_palm
    assert_no_time "palm"
  end

  # time_corpus.rs:4969
  def test_negative_mlk_day_typo
    assert_no_time "Martin Luther King' day"
  end

  # time_corpus.rs:4974
  def test_negative_two_three
    assert_no_time "two three"
  end
end
