# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeOpenIntervalAfterTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:2940
  def test_time_asap
    assert_time_open_interval_after "ASAP", [2013, 2, 12, 4, 30, 0], :second
    assert_time_open_interval_after "as soon as possible", [2013, 2, 12, 4, 30, 0], :second
  end

  # time_corpus.rs:2952
  def test_time_after_2pm
    assert_time_open_interval_after "after 2 pm", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_open_interval_after "from 2 pm", [2013, 2, 12, 14, 0, 0], :hour
    assert_time_open_interval_after "since 2pm", [2013, 2, 12, 14, 0, 0], :hour
  end

  # time_corpus.rs:2959
  def test_time_anytime_after_2014
    assert_time_open_interval_after "anytime after 2014", [2014, 1, 1, 0, 0, 0], :year
    assert_time_open_interval_after "since 2014", [2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:2971
  def test_time_after_5_days
    assert_time_open_interval_after "after 5 days", [2013, 2, 17, 4, 0, 0], :hour
  end
end
