# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/time_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTimeOpenIntervalBeforeTest < Minitest::Test
  include WaferMatchers

  # time_corpus.rs:2946
  def test_time_until_2pm
    assert_time_open_interval_before "until 2:00pm", [2013, 2, 12, 14, 0, 0], :minute
    assert_time_open_interval_before "through 2:00pm", [2013, 2, 12, 14, 0, 0], :minute
  end

  # time_corpus.rs:2965
  def test_time_before_2014
    assert_time_open_interval_before "sometimes before 2014", [2014, 1, 1, 0, 0, 0], :year
    assert_time_open_interval_before "through 2014", [2014, 1, 1, 0, 0, 0], :year
  end

  # time_corpus.rs:2976
  def test_time_before_11_am
    assert_time_open_interval_before "before 11 am", [2013, 2, 12, 11, 0, 0], :hour
  end
end
