# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/email_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferEmailEmailTest < Minitest::Test
  include WaferMatchers

  # email_corpus.rs:40
  def test_email_alice_at_example
    assert_email "alice at exAmple.io", "alice@exAmple.io"
  end

  # email_corpus.rs:45
  def test_email_yo_plus_yo
    assert_email "yo+yo at blah.org", "yo+yo@blah.org"
  end

  # email_corpus.rs:50
  def test_email_1234_abc
    assert_email "1234+abc at x.net", "1234+abc@x.net"
  end

  # email_corpus.rs:55
  def test_email_jean_jacques
    assert_email "jean-jacques at stuff.co.uk", "jean-jacques@stuff.co.uk"
  end

  # email_corpus.rs:60
  def test_email_asdf_ab_dot_c
    assert_email "asdf+ab dot c at gmail dot com", "asdf+ab.c@gmail.com"
  end

  # email_corpus.rs:65
  def test_email_asdf_dot_k
    assert_email "asdf dot k@fb dot com", "asdf.k@fb.com"
  end
end
