# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/email_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferEmailNoEmailTest < Minitest::Test
  include WaferMatchers

  # email_corpus.rs:71
  def test_email_negative_fitness
    assert_no_email "fitness at 6.40"
  end

  # email_corpus.rs:76
  def test_email_negative_class
    assert_no_email "class at 12.00"
  end

  # email_corpus.rs:81
  def test_email_negative_tonight
    assert_no_email "tonight at 9.15"
  end

  # email_corpus.rs:86
  def test_email_negative_dot_before
    assert_no_email " dot 2@abci"
  end

  # email_corpus.rs:91
  def test_email_negative_at_dot
    assert_no_email "x@ dot x"
  end

  # email_corpus.rs:96
  def test_email_negative_at_x_dot
    assert_no_email "x@ x dot "
  end

  # email_corpus.rs:101
  def test_email_negative_abc_at_x_dot
    assert_no_email "abc@x dot "
  end
end
