# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/ordinal_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferOrdinalOrdinalTest < Minitest::Test
  include WaferMatchers

  # ordinal_corpus.rs:24
  def test_ordinal_first
    assert_ordinal "first", 1
    assert_ordinal "1st", 1
  end

  # ordinal_corpus.rs:31
  def test_ordinal_second
    assert_ordinal "second", 2
    assert_ordinal "2nd", 2
  end

  # ordinal_corpus.rs:38
  def test_ordinal_third
    assert_ordinal "third", 3
    assert_ordinal "3rd", 3
  end

  # ordinal_corpus.rs:45
  def test_ordinal_fourth
    assert_ordinal "fourth", 4
    assert_ordinal "4th", 4
  end

  # ordinal_corpus.rs:52
  def test_ordinal_eighth
    assert_ordinal "eighth", 8
    assert_ordinal "8th", 8
  end

  # ordinal_corpus.rs:59
  def test_ordinal_twenty_fifth
    assert_ordinal "twenty-fifth", 25
    assert_ordinal "twenty\u2014fifth", 25
    assert_ordinal "twenty fifth", 25
    assert_ordinal "twentyfifth", 25
    assert_ordinal "25th", 25
  end

  # ordinal_corpus.rs:69
  def test_ordinal_thirty_first
    assert_ordinal "thirty-first", 31
    assert_ordinal "thirty\u2014first", 31
    assert_ordinal "thirty first", 31
    assert_ordinal "thirtyfirst", 31
    assert_ordinal "31st", 31
  end

  # ordinal_corpus.rs:79
  def test_ordinal_forty_second
    assert_ordinal "forty-second", 42
    assert_ordinal "forty\u2014second", 42
    assert_ordinal "forty second", 42
    assert_ordinal "fortysecond", 42
    assert_ordinal "42nd", 42
  end

  # ordinal_corpus.rs:89
  def test_ordinal_seventy_third
    assert_ordinal "seventy-third", 73
    assert_ordinal "seventy\u2014third", 73
    assert_ordinal "seventy third", 73
    assert_ordinal "seventythird", 73
    assert_ordinal "73rd", 73
  end

  # ordinal_corpus.rs:99
  def test_ordinal_ninetieth
    assert_ordinal "ninetieth", 90
    assert_ordinal "90th", 90
  end
end
