# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/quantity_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferQuantityQuantityTest < Minitest::Test
  include WaferMatchers

  # quantity_corpus.rs:80
  def test_quantity_2_grams
    assert_quantity "2 grams", 2.0, "gram"
    assert_quantity "0.002 kg", 2.0, "gram"
    assert_quantity "2 g.", 2.0, "gram"
    assert_quantity "2 gs", 2.0, "gram"
    assert_quantity "2/1000 kilograms", 2.0, "gram"
    assert_quantity "2000 milligrams", 2.0, "gram"
    assert_quantity "2,000 milligrams", 2.0, "gram"
  end

  # quantity_corpus.rs:92
  def test_quantity_1_kilogram
    assert_quantity "a kilogram", 1000.0, "gram"
    assert_quantity "a kg", 1000.0, "gram"
    assert_quantity "1 k.g.", 1000.0, "gram"
    assert_quantity "1 k.gs", 1000.0, "gram"
    assert_quantity "1000 gs", 1000.0, "gram"
  end

  # quantity_corpus.rs:102
  def test_quantity_1_pound
    assert_quantity "a Pound", 1.0, "pound"
    assert_quantity "1 lb", 1.0, "pound"
    assert_quantity "a lb", 1.0, "pound"
  end

  # quantity_corpus.rs:110
  def test_quantity_2_ounces
    assert_quantity "2 ounces", 2.0, "ounce"
    assert_quantity "2oz", 2.0, "ounce"
  end

  # quantity_corpus.rs:124
  def test_quantity_three_quarter_cup
    assert_quantity "3/4 cup", 0.75, "cup"
    assert_quantity "0.75 cup", 0.75, "cup"
    assert_quantity ".75 cups", 0.75, "cup"
  end

  # quantity_corpus.rs:176
  def test_quantity_2_7g
    assert_quantity "around 2 -7 g", 2.0, "gram"
    assert_quantity "~2-7 grams", 2.0, "gram"
    assert_quantity "from 2 to 7 g", 2.0, "gram"
    assert_quantity "between 2.0 g and about 7.0 g", 2.0, "gram"
    assert_quantity "between 0.002 kg and about 0.007 kg", 2.0, "gram"
    assert_quantity "2 - ~7 grams", 2.0, "gram"
  end

  # quantity_corpus.rs:196
  def test_quantity_above_2_cups
    assert_quantity "exceeding 2 Cups", 2.0, "cup"
    assert_quantity "at least two Cups", 2.0, "cup"
    assert_quantity "over 2 Cups", 2.0, "cup"
    assert_quantity "more than 2 Cups", 2.0, "cup"
  end
end
