# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/quantity_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferQuantityWithProductTest < Minitest::Test
  include WaferMatchers

  # quantity_corpus.rs:74
  def test_quantity_2_pounds_meat
    assert_quantity_with_product "two pounds of meat", 2.0, "pound", "meat"
  end

  # quantity_corpus.rs:117
  def test_quantity_3_cups_sugar
    assert_quantity_with_product "3 Cups of sugar", 3.0, "cup", "sugar"
    assert_quantity_with_product "3 Cups of SugAr", 3.0, "cup", "sugar"
  end

  # quantity_corpus.rs:132
  def test_quantity_500g_strawberries
    assert_quantity_with_product "500 grams of strawberries", 500.0, "gram", "strawberries"
    assert_quantity_with_product "500g of strawberries", 500.0, "gram", "strawberries"
    assert_quantity_with_product "0.5 kilograms of strawberries", 500.0, "gram", "strawberries"
    assert_quantity_with_product "0.5 kg of strawberries", 500.0, "gram", "strawberries"
    assert_quantity_with_product "500000mg of strawberries", 500.0, "gram", "strawberries"
  end

  # quantity_corpus.rs:147
  def test_quantity_100_1000g_strawberries
    assert_quantity_with_product "100-1000 gram of strawberries", 100.0, "gram", "strawberries"
    assert_quantity_with_product "between 100 and 1000 grams of strawberries", 100.0, "gram", "strawberries"
    assert_quantity_with_product "from 100 to 1000 g of strawberries", 100.0, "gram", "strawberries"
    assert_quantity_with_product "100 - 1000 g of strawberries", 100.0, "gram", "strawberries"
  end

  # quantity_corpus.rs:187
  def test_quantity_under_6_pounds_meat
    assert_quantity_with_product "less than six pounds of meat", 6.0, "pound", "meat"
    assert_quantity_with_product "no more than 6 lbs of meat", 6.0, "pound", "meat"
    assert_quantity_with_product "below 6.0 pounds of meat", 6.0, "pound", "meat"
    assert_quantity_with_product "at most six pounds of meat", 6.0, "pound", "meat"
  end

  # quantity_corpus.rs:205
  def test_quantity_above_4oz_chocolate
    assert_quantity_with_product "exceeding 4 oz of chocolate", 4.0, "ounce", "chocolate"
    assert_quantity_with_product "at least 4.0 oz of chocolate", 4.0, "ounce", "chocolate"
    assert_quantity_with_product "over four ounces of chocolate", 4.0, "ounce", "chocolate"
    assert_quantity_with_product "more than four ounces of chocolate", 4.0, "ounce", "chocolate"
  end
end
