# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/temperature_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferTemperatureTemperatureTest < Minitest::Test
  include WaferMatchers

  # temperature_corpus.rs:43
  def test_temp_37_celsius
    assert_temperature "37\u00B0C", 37.0, "celsius"
    assert_temperature "37 \u00B0 celsius", 37.0, "celsius"
    assert_temperature "37 degrees Celsius", 37.0, "celsius"
    assert_temperature "thirty seven celsius", 37.0, "celsius"
    assert_temperature "37 degrees Celsius", 37.0, "celsius"
    assert_temperature "thirty seven celsius", 37.0, "celsius"
  end

  # temperature_corpus.rs:54
  def test_temp_70_fahrenheit
    assert_temperature "70\u00B0F", 70.0, "fahrenheit"
    assert_temperature "70 \u00B0 Fahrenheit", 70.0, "fahrenheit"
    assert_temperature "70 degrees F", 70.0, "fahrenheit"
    assert_temperature "seventy Fahrenheit", 70.0, "fahrenheit"
  end

  # temperature_corpus.rs:63
  def test_temp_98_6_fahrenheit
    assert_temperature "98.6\u00B0F", 98.6, "fahrenheit"
    assert_temperature "98.6 \u00B0 Fahrenheit", 98.6, "fahrenheit"
    assert_temperature "98.6 degrees F", 98.6, "fahrenheit"
  end

  # temperature_corpus.rs:71
  def test_temp_45_degree
    assert_temperature "45\u00B0", 45.0, "degree"
    assert_temperature "45 degrees", 45.0, "degree"
    assert_temperature "45 deg.", 45.0, "degree"
  end

  # temperature_corpus.rs:79
  def test_temp_negative_2_degree
    assert_temperature "-2\u00B0", -2.0, "degree"
    assert_temperature "- 2 degrees", -2.0, "degree"
    assert_temperature "2 degrees below zero", -2.0, "degree"
    assert_temperature "2 below zero", -2.0, "degree"
  end

  # temperature_corpus.rs:88
  def test_temp_between_30_40_degree
    assert_temperature "between 30 and 40 degrees", 30.0, "degree"
    assert_temperature "from 30 degrees to 40 degrees", 30.0, "degree"
  end

  # temperature_corpus.rs:95
  def test_temp_between_30_40_celsius
    assert_temperature "between 30 and 40 celsius", 30.0, "celsius"
    assert_temperature "from 30 celsius and 40 celsius", 30.0, "celsius"
    assert_temperature "between 30 and 40 degrees celsius", 30.0, "celsius"
    assert_temperature "from 30 degrees celsius to 40 degrees celsius", 30.0, "celsius"
    assert_temperature "30-40 degrees celsius", 30.0, "celsius"
  end

  # temperature_corpus.rs:109
  def test_temp_above_40_degree
    assert_temperature "over 40 degrees", 40.0, "degree"
    assert_temperature "at least 40 degrees", 40.0, "degree"
    assert_temperature "more than 40 degrees", 40.0, "degree"
  end

  # temperature_corpus.rs:117
  def test_temp_under_40_degree
    assert_temperature "under 40 degrees", 40.0, "degree"
    assert_temperature "less than 40 degrees", 40.0, "degree"
    assert_temperature "lower than 40 degrees", 40.0, "degree"
  end
end
