# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/phone_number_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferPhoneNumberNoPhoneTest < Minitest::Test
  include WaferMatchers

  # phone_number_corpus.rs:93
  def test_phone_negative_short
    assert_no_phone "12345"
  end

  # phone_number_corpus.rs:98
  def test_phone_negative_too_long
    assert_no_phone "1234567890123456777777"
    assert_no_phone "12345678901234567"
  end
end
