# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/phone_number_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferPhoneNumberPhoneTest < Minitest::Test
  include WaferMatchers

  # phone_number_corpus.rs:40
  def test_phone_650_701_8887
    assert_phone "650-701-8887", "6507018887"
  end

  # phone_number_corpus.rs:45
  def test_phone_plus1_650
    assert_phone "(+1)650-701-8887", "(+1) 6507018887"
    assert_phone "(+1)   650 - 701  8887", "(+1) 6507018887"
    assert_phone "(+1) 650-701-8887", "(+1) 6507018887"
    assert_phone "+1 6507018887", "(+1) 6507018887"
  end

  # phone_number_corpus.rs:53
  def test_phone_plus33
    assert_phone "+33 1 46647998", "(+33) 146647998"
  end

  # phone_number_corpus.rs:58
  def test_phone_06_2070
    assert_phone "06 2070 2220", "0620702220"
  end

  # phone_number_corpus.rs:63
  def test_phone_with_ext
    assert_phone "(650)-701-8887 ext 897", "6507018887 ext 897"
  end

  # phone_number_corpus.rs:68
  def test_phone_plus1_202
    assert_phone "+1-202-555-0121", "(+1) 2025550121"
    assert_phone "+1 202.555.0121", "(+1) 2025550121"
  end

  # phone_number_corpus.rs:74
  def test_phone_dots
    assert_phone "4.8.6.6.8.2.7", "4866827"
  end

  # phone_number_corpus.rs:79
  def test_phone_plain_digits
    assert_phone "06354640807", "06354640807"
    assert_phone "18998078030", "18998078030"
  end

  # phone_number_corpus.rs:85
  def test_phone_brazil_format
    assert_phone "61 - 9 9285-2776", "61992852776"
    assert_phone "(19) 997424919", "19997424919"
    assert_phone "+55 19992842606", "(+55) 19992842606"
  end
end
