# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus_local.json.
# Upstream: hand-written local additions, not extracted from upstream
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferLocalTimeIntervalTest < Minitest::Test
  include WaferMatchers

  # local_by_deadline:1
  def test_by_named_weekday
    assert_time_interval "by Friday", [2013, 2, 12, 4, 30, 0], [2013, 2, 15, 0, 0, 0], :second
    assert_time_interval "by next monday", [2013, 2, 12, 4, 30, 0], [2013, 2, 18, 0, 0, 0], :second
  end

  # local_by_deadline:3
  def test_by_full_date
    assert_time_interval "by Friday July 3, 2026", [2013, 2, 12, 4, 30, 0], [2026, 7, 3, 0, 0, 0], :second
    assert_time_interval "by March 1st", [2013, 2, 12, 4, 30, 0], [2013, 3, 1, 0, 0, 0], :second
  end

  # local_by_deadline:5
  def test_by_day_of_month
    assert_time_interval "by the 15th", [2013, 2, 12, 4, 30, 0], [2013, 2, 15, 0, 0, 0], :second
  end

  # local_by_deadline:6
  def test_by_relative_day
    assert_time_interval "by tomorrow", [2013, 2, 12, 4, 30, 0], [2013, 2, 13, 0, 0, 0], :second
  end
end
