# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/credit_card_number_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferCreditCardNumberCcTest < Minitest::Test
  include WaferMatchers

  # credit_card_number_corpus.rs:42
  def test_cc_visa
    assert_credit_card "4111111111111111", "4111111111111111", "visa"
    assert_credit_card "4111-1111-1111-1111", "4111111111111111", "visa"
  end

  # credit_card_number_corpus.rs:49
  def test_cc_amex
    assert_credit_card "371449635398431", "371449635398431", "amex"
    assert_credit_card "3714-496353-98431", "371449635398431", "amex"
  end

  # credit_card_number_corpus.rs:56
  def test_cc_discover
    assert_credit_card "6011111111111117", "6011111111111117", "discover"
    assert_credit_card "6011-1111-1111-1117", "6011111111111117", "discover"
  end

  # credit_card_number_corpus.rs:63
  def test_cc_mastercard
    assert_credit_card "5555555555554444", "5555555555554444", "mastercard"
    assert_credit_card "5555-5555-5555-4444", "5555555555554444", "mastercard"
  end

  # credit_card_number_corpus.rs:70
  def test_cc_diners_club
    assert_credit_card "30569309025904", "30569309025904", "dinerclub"
    assert_credit_card "3056-930902-5904", "30569309025904", "dinerclub"
  end

  # credit_card_number_corpus.rs:77
  def test_cc_other
    assert_credit_card "3530111333300000", "3530111333300000", "other"
  end
end
