# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/credit_card_number_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferCreditCardNumberNoCcTest < Minitest::Test
  include WaferMatchers

  # credit_card_number_corpus.rs:83
  def test_cc_negative_invalid_luhn
    assert_no_credit_card "4111111111111110"
    assert_no_credit_card "371449635398430"
    assert_no_credit_card "6011111111111110"
    assert_no_credit_card "5555555555554440"
    assert_no_credit_card "30569309025900"
  end

  # credit_card_number_corpus.rs:93
  def test_cc_negative_wrong_format
    assert_no_credit_card "41111111-1111-1111"
    assert_no_credit_card "3714496353-98431"
    assert_no_credit_card "60111111-1111-1117"
    assert_no_credit_card "55555555-5555-4444"
    assert_no_credit_card "3056930902-5904"
  end

  # credit_card_number_corpus.rs:103
  def test_cc_negative_other
    assert_no_credit_card "invalid"
  end
end
