# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/numeral_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferNumeralNumeralTest < Minitest::Test
  include WaferMatchers

  # numeral_corpus.rs:24
  def test_numeral_zero
    assert_numeral "0", 0.0
    assert_numeral "naught", 0.0
    assert_numeral "nought", 0.0
    assert_numeral "zero", 0.0
    assert_numeral "nil", 0.0
  end

  # numeral_corpus.rs:34
  def test_numeral_one
    assert_numeral "1", 1.0
    assert_numeral "one", 1.0
    assert_numeral "single", 1.0
  end

  # numeral_corpus.rs:42
  def test_numeral_two
    assert_numeral "2", 2.0
    assert_numeral "two", 2.0
    assert_numeral "a pair", 2.0
    assert_numeral "a couple", 2.0
    assert_numeral "a couple of", 2.0
  end

  # numeral_corpus.rs:52
  def test_numeral_three
    assert_numeral "3", 3.0
    assert_numeral "three", 3.0
    assert_numeral "a few", 3.0
    assert_numeral "few", 3.0
  end

  # numeral_corpus.rs:61
  def test_numeral_ten
    assert_numeral "10", 10.0
    assert_numeral "ten", 10.0
  end

  # numeral_corpus.rs:68
  def test_numeral_twelve
    assert_numeral "12", 12.0
    assert_numeral "twelve", 12.0
    assert_numeral "a dozen", 12.0
    assert_numeral "a dozen of", 12.0
  end

  # numeral_corpus.rs:77
  def test_numeral_fourteen
    assert_numeral "14", 14.0
    assert_numeral "fourteen", 14.0
  end

  # numeral_corpus.rs:84
  def test_numeral_sixteen
    assert_numeral "16", 16.0
    assert_numeral "sixteen", 16.0
  end

  # numeral_corpus.rs:91
  def test_numeral_seventeen
    assert_numeral "17", 17.0
    assert_numeral "seventeen", 17.0
  end

  # numeral_corpus.rs:98
  def test_numeral_eighteen
    assert_numeral "18", 18.0
    assert_numeral "eighteen", 18.0
  end

  # numeral_corpus.rs:105
  def test_numeral_thirty_three
    assert_numeral "33", 33.0
    assert_numeral "thirty three", 33.0
    assert_numeral "0033", 33.0
  end

  # numeral_corpus.rs:113
  def test_numeral_twenty_four
    assert_numeral "24", 24.0
    assert_numeral "2 dozens", 24.0
    assert_numeral "two dozen", 24.0
    assert_numeral "Two dozen", 24.0
  end

  # numeral_corpus.rs:122
  def test_numeral_one_point_one
    assert_numeral "1.1", 1.1
    assert_numeral "1.10", 1.1
    assert_numeral "01.10", 1.1
    assert_numeral "1 point 1", 1.1
  end

  # numeral_corpus.rs:131
  def test_numeral_point_seven_seven
    assert_numeral ".77", 0.77
    assert_numeral "0.77", 0.77
    assert_numeral "point 77", 0.77
  end

  # numeral_corpus.rs:139
  def test_numeral_hundred_thousand
    assert_numeral "100,000", 100000.0
    assert_numeral "100,000.0", 100000.0
    assert_numeral "100000", 100000.0
    assert_numeral "100K", 100000.0
    assert_numeral "100k", 100000.0
    assert_numeral "one hundred thousand", 100000.0
  end

  # numeral_corpus.rs:150
  def test_numeral_fractions
    assert_numeral "1/5", 0.2
    assert_numeral "2/10", 0.2
    assert_numeral "3/15", 0.2
    assert_numeral "20/100", 0.2
  end

  # numeral_corpus.rs:159
  def test_numeral_three_million
    assert_numeral "3M", 3000000.0
    assert_numeral "3000K", 3000000.0
    assert_numeral "3000000", 3000000.0
    assert_numeral "3,000,000", 3000000.0
    assert_numeral "3 million", 3000000.0
    assert_numeral "30 lakh", 3000000.0
    assert_numeral "30 lkh", 3000000.0
    assert_numeral "30 l", 3000000.0
  end

  # numeral_corpus.rs:172
  def test_numeral_one_point_two_million
    assert_numeral "1,200,000", 1200000.0
    assert_numeral "1200000", 1200000.0
    assert_numeral "1.2M", 1200000.0
    assert_numeral "1200k", 1200000.0
    assert_numeral ".0012G", 1200000.0
    assert_numeral "12 lakhs", 1200000.0
    assert_numeral "12 lkhs", 1200000.0
  end

  # numeral_corpus.rs:184
  def test_numeral_five_thousand
    assert_numeral "5 thousand", 5000.0
    assert_numeral "five thousand", 5000.0
  end

  # numeral_corpus.rs:191
  def test_numeral_negative_504
    assert_numeral "-504", -504.0
    assert_numeral "negative five hundred and four", -504.0
  end

  # numeral_corpus.rs:198
  def test_numeral_negative_1_2_million
    assert_numeral "- 1,200,000", -1200000.0
    assert_numeral "-1200000", -1200000.0
    assert_numeral "minus 1,200,000", -1200000.0
    assert_numeral "negative 1200000", -1200000.0
    assert_numeral "-1.2M", -1200000.0
    assert_numeral "-1200K", -1200000.0
    assert_numeral "-.0012G", -1200000.0
  end

  # numeral_corpus.rs:210
  def test_numeral_negative_3_2_million
    assert_numeral "-3,200,000", -3200000.0
    assert_numeral "-3200000", -3200000.0
    assert_numeral "minus three million two hundred thousand", -3200000.0
  end

  # numeral_corpus.rs:218
  def test_numeral_one_twenty_two
    assert_numeral "one twenty two", 122.0
    assert_numeral "ONE TwentY tWO", 122.0
  end

  # numeral_corpus.rs:225
  def test_numeral_two_hundred_thousand
    assert_numeral "two Hundred thousand", 200000.0
  end

  # numeral_corpus.rs:231
  def test_numeral_twenty_one_thousand_eleven
    assert_numeral "twenty-one thousand Eleven", 21011.0
  end

  # numeral_corpus.rs:237
  def test_numeral_seven_hundred_twenty_one_thousand_twelve
    assert_numeral "seven hundred twenty-one thousand twelve", 721012.0
    assert_numeral "seven hundred twenty-one thousand and twelve", 721012.0
  end

  # numeral_corpus.rs:244
  def test_numeral_thirty_one_million
    assert_numeral "thirty-one million two hundred fifty-six thousand seven hundred twenty-one", 31256721.0
    assert_numeral "three crore twelve lakh fifty-six thousand seven hundred twenty-one", 31256721.0
    assert_numeral "three cr twelve lac fifty-six thousand seven hundred twenty-one", 31256721.0
  end

  # numeral_corpus.rs:261
  def test_numeral_two_hundred_dozens
    assert_numeral "two hundred dozens", 2400.0
    assert_numeral "200 dozens", 2400.0
  end

  # numeral_corpus.rs:268
  def test_numeral_two_point_two_million
    assert_numeral "two point two million", 2200000.0
  end

  # numeral_corpus.rs:274
  def test_numeral_three_billion
    assert_numeral "three billions", 3000000000.0
    assert_numeral "three thousand millions", 3000000000.0
    assert_numeral "three hundred crores", 3000000000.0
    assert_numeral "three hundred Cr", 3000000000.0
    assert_numeral "three hundred koti", 3000000000.0
    assert_numeral "three hundred krores", 3000000000.0
    assert_numeral "three hundred Kr", 3000000000.0
  end

  # numeral_corpus.rs:286
  def test_numeral_forty_five
    assert_numeral "forty-five (45)", 45.0
    assert_numeral "45 (forty five)", 45.0
  end
end
