require_relative "gh"
require "json"
P0 = ids.fetch("p0"); P1 = ids.fetch("p1")

DIMS = [
  {slug: "numeral", name: "numeral", rules: 23, files: "`src/dimensions/numeral/en.rs` (629 lines) + `src/dimensions/numeral/mod.rs` (93)",
   corpus: "105 numeral corpus cases (#157)",
   note: "Every `TimeForm` slice that takes an integer — `DayOfMonth`, `Year`, `NthGrain`, `NDOWsFromTime`, `RelativeGrain` — consumes numeral tokens through `integer_value()`/`numeral_data()`. This slice is on the critical path for most of Wave A even though it is not a time slice."},
  {slug: "duration", name: "duration", rules: 20, files: "`src/dimensions/duration/en.rs` (436 lines) + `src/dimensions/duration/mod.rs` (68)",
   corpus: "83 duration corpus cases (#157)",
   note: "`DurationAfter` (Wave B) and six of `Interval`'s rules (`<time> for <duration>`, `from <time> for <duration>`, `within <duration>`) consume duration tokens. `normalized_seconds` is part of the emitted value shape."},
  {slug: "ordinal", name: "ordinal", rules: 4, files: "`src/dimensions/ordinal/en.rs` (166 lines) + `src/dimensions/ordinal/mod.rs` (52)",
   corpus: "32 ordinal corpus cases (#157)",
   note: "Four rules, the smallest slice in the tree. `NthGrain`, `NthDOWOfTime`, `NthGrainOfTime`, `NthLastDayOfTime`, `NthLastCycleOfTime` and the `<ordinal> <month>` date rules all consume ordinal tokens."},
  {slug: "time_grain", name: "time-grain", rules: 8, files: "`src/dimensions/time_grain/en.rs` (91 lines) + `src/dimensions/time_grain/mod.rs` (162)",
   corpus: "no dedicated corpus file — grain is asserted as the second argument of every `check_time_naive`/`check_time_instant` case, so its coverage comes through the time slices",
   note: "`Grain` is the enum every time slice's resolved value carries. `mod.rs` (162 lines) holds the ordering and the `as_str()` mapping that produces the lowercase-snake_case symbols (`:second`, `:no_grain`, …) the Ruby side must emit — see AGENTS.md's \"Entity `:value` shapes\". This slice is a hard blocker for the fixture format itself."}
]

created = {}
DIMS.each do |d|
  body = <<~MD
    Parent: #163 · Phase 2 · Wave A · dependency dimension **#{d[:name]}**

    **Runs alongside Wave A, independent of it.** The four dependency-dimension slices have no ordering constraint against each other or against any `TimeForm` slice — but most Wave A time slices consume their tokens, so these want to start first in practice.

    Blocked by ##{P0} (base classes, fixture format) and ##{P1} (your fixture file).

    ## Scope

    Port the #{d[:rules]} EN #{d[:name]} rules and the dimension's value shape.

    Rust source: #{d[:files]} — duckling 0.4.0.

    #{d[:note]}

    ## Value shape

    The emitted `:value` must match what the native backend emits today, exactly as AGENTS.md's "Entity `:value` shapes" documents it. The corpus is the oracle: #{d[:corpus]}.

    ## Files you create. No other slice touches them

    - `lib/duckling/ruby/rules/en/#{d[:slug]}.rb` — the rules, appending to the rule set on load
    - `lib/duckling/ruby/dimensions/#{d[:slug]}.rb` — the value shape and any helpers
    - `test/ruby_backend/dimensions/#{d[:slug]}_test.rb`
    - `test/fixtures/ruby_backend/#{d[:slug]}.json` — **generated by ##{P1}, never hand-edited**

    **Files you must not edit:** the engine spine, the base classes, and the fixture format are frozen ##{P0} output. File a follow-up issue for a spine gap; do not edit in place.

    ## Definition of done

    - [ ] Every fixture row in `test/fixtures/ruby_backend/#{d[:slug]}.json` passes on the Ruby backend
    - [ ] The full suite is green on the **native** backend — it must be untouched
    - [ ] No file outside the four listed above is modified

    ## Do not read the Rust rule implementations

    Decision 2 of #163: corpus-TDD, not transcription. Write Ruby from the fixture rows. Phase 3 is where a different agent reads the Rust deliberately, to find branches the corpus never exercises — reading it now destroys the differential that makes the corpus the oracle.

    Pattern strings are the exception: they are data, and PR #162 extracted all 3,418 of them to `docs/spike/duckling_patterns.json`. Take them from there.

    ## Regex dialect notes

    - `(?i)` is applied crate-wide by `pattern.rs`'s `regex()` helper. Apply the same blanket case-insensitivity.
    - Rust `regex` has no backreferences and no lookaround; Onigmo has both, so translation is one-directional and mostly verbatim.
    - Rust's leftmost-first alternation and Onigmo's backtracking order are not identical; overlapping alternation branches can match a different span.
  MD
  num = create(title: "Ruby backend Wave A — #{d[:name]} dimension (#{d[:rules]} EN rules)", body: body, labels: %w[ruby-backend wave-a test-first])
  link(163, num)
  created[d[:slug]] = num
  puts "#{d[:slug]} -> ##{num}"
end
h = ids; h["dims"] = created; File.write(File.join(__dir__, "created.json"), JSON.pretty_generate(h))
