require_relative "gh"
require "json"
SL = JSON.parse(File.read(File.join(__dir__, "slices.json")))
P0 = ids.fetch("p0"); P1 = ids.fetch("p1"); RANK = ids.fetch("rank")

WAVE_NOTE = {
  "A" => "**Wave A — leaf variant, no `TimeData` child.** Fully parallel with every other Wave A slice and with the four dependency-dimension slices. No ordering constraint of any kind inside the wave.",
  "B" => "**Wave B — single-child composite.** Takes one `TimeData` child, so it starts once Wave A is green. No ordering constraint against other Wave B slices.",
  "C" => "**Wave C — multi-child composite.** Takes two or more `TimeData` children, so it starts once Wave B is green. No ordering constraint against the other two Wave C slices."
}

EXTRA = {
  "Holiday" => "> **Sized for a split.** The corpus carries a long tail of named holidays — Eid, Ramadan, Thanksgiving, Yom Kippur, Guru Nanak, Vesak, Koningsdag, Orthodox Easter, MLK — with real calendar arithmetic behind several. #163 says explicitly: split this into sub-slices if one agent stalls on it. `holidays_regex()` at `src/dimensions/time/en.rs:4847` is the enumeration.",
  "Interval" => "> **Highest-risk slice in the tree.** It owns open intervals (13 explicit `check_time_open_interval_after`/`_before` corpus cases), end-bound adjustment, and the `by <time>` deadline synthesis #157 documents — a *closed* `[now, named]` interval where `from` equals the reference instant exactly. \"Both bounds present\" is not the same as \"both bounds stated in the text\". The third tuple field is the open flag (`true` = do not adjust the end).\n>\n> With 27 rules it is also one of the three fattest slices. Consider splitting it: the `from…to` / `between…and` explicit-range rules, the `<time> for <duration>` rules, and the `end of <grain>` / `by <time>` deadline rules are three coherent groups.",
  "Composed" => "> **Fattest slice in the tree at 34 rules**, and it carries 20 of the `TimeForm::` references in `mod.rs`'s resolver — the `PartOfDay` interaction alone spans roughly `mod.rs:993–1230`. Consider splitting into three sub-slices: the `<part-of-day>` intersections, the `<month>`/`<day-of-month>` date intersections, and the ISO/numeric formats (`yyyy-mm-dd`, `mm/yyyy`, `iso8601`).",
  "HourMinute" => "> **26 rules — third-fattest slice.** It absorbs the `apply_ampm()` rules (`src/dimensions/time/en.rs:4766`), which produce `Hour` or `HourMinute` depending on input, and it owns the 12-hour ambiguity flag that `Hour`/`HourMinute` both carry as their trailing `bool`. Consider splitting the am/pm rules from the bare clock-time rules."
}

def files_block(slug)
  <<~MD
    **Files you create. No other slice touches them:**

    - `lib/duckling/ruby/time/forms/#{slug}.rb` — the resolver, self-registering under its variant tag
    - `lib/duckling/ruby/rules/en/#{slug}.rb` — the rules, appending to the rule set on load
    - `test/ruby_backend/forms/#{slug}_test.rb`
    - `test/fixtures/ruby_backend/#{slug}.json` — **generated by ##{ids.fetch("p1")}, never hand-edited**

    **Files you must not edit:** the engine spine, the base classes, and the fixture format are frozen output of ##{ids.fetch("p0")}. If your slice needs a spine change, open a follow-up issue and link it here — do not edit in place. A hand-edited `require` manifest is likewise forbidden; loading is `Dir.glob`-based and each file self-registers.
  MD
end

PORT_RULE = <<~MD
  ## Do not read the Rust rule implementations

  Decision 2 of #163: this is **corpus-TDD, not transcription**. You write Ruby from the fixture rows and the rule names above. You do not open `src/dimensions/time/en.rs` to copy a production closure.

  Phase 3 is where the Rust gets read — by a different agent, deliberately, to find branches the corpus never exercises. Reading it now collapses the two phases and destroys the differential that makes the corpus the oracle.

  The regexes are the exception: pattern strings are data, and PR #162 already extracted all 3,418 of them to `docs/spike/duckling_patterns.json`. Take them from there.
MD

def regex_notes
  <<~MD
    ## Regex dialect notes

    - `(?i)` is applied crate-wide by `pattern.rs`'s `regex()` helper, which prefixes every pattern. Apply the same blanket case-insensitivity; do not rely on per-pattern flags.
    - Rust `regex` has no backreferences and no lookaround; Onigmo has both, so translation is one-directional and mostly verbatim.
    - `\\b` semantics differ on non-ASCII input, and the crate leans on `\\b` heavily.
    - Rust's leftmost-first alternation and Onigmo's backtracking order are not identical. A rule whose alternation branches overlap can match a different span — this is the most likely source of a fixture row that fails on span rather than on value.
  MD
end

created = {}
SL.each do |s|
  wave = s["wave"]; key = s["key"]; slug = s["slug"]
  n = s["rules"].size
  if s["kind"] == "modifiers"
    title = "Ruby backend Wave A — modifier and absorption rules (#{n} EN rules, no TimeForm of their own)"
    scope = <<~MD
      ## Scope — a slice #163 does not name

      **#163's slicing plan has 37 `TimeForm` variants and 221 EN rules, but 23 of those rules construct no `TimeForm` at all.** They clone an existing `TimeData` and mutate its attribute fields. They have no variant to be sliced by, so without this issue they would be orphaned — every one of the 37 variant slices would either skip them or all reach for them at once.

      These rules own the `TimeData` attribute fields rather than the `form` field:

      | Attribute | What sets it |
      |---|---|
      | `latent` | almost every rule here — promoting a latent token to a real one |
      | `early_late` | `late/early/mid <time>`, `part of <named-month>` |
      | `open_interval_direction` | `until <time>`, `from\\|since\\|after <time>`, `after <part-of-day>` |
      | `timezone` | `<time> timezone`, `<time> (timezone)` |
      | `direction` | `this past weekend`, `last <time>`, `next <time>`, `<time> before last\\|after next` |

      Those fields are declared on `TimeData` in `src/dimensions/time/mod.rs` and are therefore **##{P0} output** — this slice mutates them, it does not define them. If a field is missing from ##{P0}'s `TimeData`, that is a spine follow-up, not an edit here.
    MD
    rules_tbl = "| Rust rule name | fields it mutates |\n|---|---|\n" +
      s["rules"].map { |r| "| `#{r["name"].gsub("|", "\\|").gsub('\\"', '"')}` | #{(r["mods"] || []).empty? ? "—" : r["mods"].map { |m| "`#{m}`" }.join(", ")} |" }.join("\n")
  else
    title = "Ruby backend Wave #{wave} — TimeForm::#{key} (#{n} EN rule#{"s" unless n == 1})"
    scope = <<~MD
      ## The variant

      ```rust
      // src/dimensions/time/mod.rs — duckling 0.4.0
      #{s["excerpt"]}
      ```

      Its resolution logic is spread across several functions in `src/dimensions/time/mod.rs` (#{s["mod_hits"]} `TimeForm::#{key}` reference#{"s" unless s["mod_hits"] == 1}), not one match arm. `grep -n 'TimeForm::#{key}' src/dimensions/time/mod.rs` is the entry point — **for Phase 3, not for this issue** (see below).
    MD
    rules_tbl = "| Rust rule name |\n|---|\n" + s["rules"].map { |r| "| `#{r["name"].gsub("|", "\\|").gsub('\\"', '"')}` |" }.join("\n")
    rules_tbl = "_None. This variant is constructed only by other slices' rules; your job is the resolver and its fixture rows._" if n.zero?
  end

  body = <<~MD
    Parent: #163 · Phase 2 · Wave #{wave} · slice **`#{key}`**

    #{WAVE_NOTE[wave]}

    Blocked by ##{P0} (base classes, fixture format) and ##{P1} (your fixture file). Ranking (##{RANK}) runs in parallel and is not a blocker for this slice's own fixture rows.

    #{EXTRA[key] ? EXTRA[key] + "\n" : ""}
    #{scope}
    ## Rules you own (#{n})

    Ownership is exclusive: **a rule is owned by the highest-wave variant it constructs.** `"tomorrow morning"` builds `Composed(Tomorrow, PartOfDay)`, so it is a Wave C `Composed` rule, not a Wave A `Tomorrow` rule. That is what makes the assignment conflict-free across all 38 slices, and it is the same rule Phase 1 uses to bucket fixture cases.

    #{rules_tbl}

    #{files_block(slug)}
    ## Definition of done

    - [ ] Every fixture row in `test/fixtures/ruby_backend/#{slug}.json` passes on the Ruby backend
    - [ ] The full suite is green on the **native** backend — it must be untouched
    - [ ] No file outside the four listed above is modified
    - [ ] Any spine gap found is filed as a follow-up issue and linked here, not patched in place

    #{PORT_RULE}
    #{regex_notes}
  MD

  num = create(title: title, body: body, labels: ["ruby-backend", "wave-#{wave.downcase}", "test-first"])
  link(163, num)
  created[key] = num
  puts "#{key} -> ##{num}"
end
h = ids; h["phase2"] = created; File.write(File.join(__dir__, "created.json"), JSON.pretty_generate(h))
