# frozen_string_literal: true

# Generated by `rake corpus:generate` from test/fixtures/wafer_corpus.json.
# Upstream: wafer-inc/duckling @ c96b068, tests/volume_corpus.rs
# Do not edit by hand. See docs/wafer-corpus.md.

require "test_helper"

class WaferVolumeVolumeTest < Minitest::Test
  include WaferMatchers

  # volume_corpus.rs:43
  def test_volume_1_litre
    assert_volume "1 liter", 1.0, "litre"
    assert_volume "1 litre", 1.0, "litre"
    assert_volume "one liter", 1.0, "litre"
    assert_volume "a liter", 1.0, "litre"
  end

  # volume_corpus.rs:52
  def test_volume_2_litres
    assert_volume "2 liters", 2.0, "litre"
    assert_volume "2l", 2.0, "litre"
  end

  # volume_corpus.rs:59
  def test_volume_1000_litres
    assert_volume "1000 liters", 1000.0, "litre"
    assert_volume "thousand liters", 1000.0, "litre"
  end

  # volume_corpus.rs:66
  def test_volume_half_litre
    assert_volume "half liter", 0.5, "litre"
    assert_volume "half-litre", 0.5, "litre"
    assert_volume "half a liter", 0.5, "litre"
  end

  # volume_corpus.rs:74
  def test_volume_quarter_litre
    assert_volume "quarter-litre", 0.25, "litre"
    assert_volume "fourth of liter", 0.25, "litre"
  end

  # volume_corpus.rs:81
  def test_volume_1_ml
    assert_volume "one milliliter", 1.0, "millilitre"
    assert_volume "an ml", 1.0, "millilitre"
    assert_volume "a millilitre", 1.0, "millilitre"
  end

  # volume_corpus.rs:89
  def test_volume_250_ml
    assert_volume "250 milliliters", 250.0, "millilitre"
    assert_volume "250 millilitres", 250.0, "millilitre"
    assert_volume "250ml", 250.0, "millilitre"
    assert_volume "250mls", 250.0, "millilitre"
    assert_volume "250 ml", 250.0, "millilitre"
  end

  # volume_corpus.rs:99
  def test_volume_3_gallons
    assert_volume "3 gallons", 3.0, "gallon"
    assert_volume "3 gal", 3.0, "gallon"
    assert_volume "3gal", 3.0, "gallon"
    assert_volume "around three gallons", 3.0, "gallon"
  end

  # volume_corpus.rs:108
  def test_volume_half_gallon
    assert_volume "0.5 gals", 0.5, "gallon"
    assert_volume "1/2 gallon", 0.5, "gallon"
    assert_volume "half a gallon", 0.5, "gallon"
  end

  # volume_corpus.rs:116
  def test_volume_tenth_gallon
    assert_volume "0.1 gallons", 0.1, "gallon"
    assert_volume "tenth of a gallon", 0.1, "gallon"
  end

  # volume_corpus.rs:123
  def test_volume_3_hectolitres
    assert_volume "3 hectoliters", 3.0, "hectolitre"
  end

  # volume_corpus.rs:129
  def test_volume_between_100_1000_litres
    assert_volume "between 100 and 1000 liters", 100.0, "litre"
    assert_volume "100-1000 liters", 100.0, "litre"
    assert_volume "from 100 to 1000 l", 100.0, "litre"
    assert_volume "100 - 1000 l", 100.0, "litre"
  end

  # volume_corpus.rs:138
  def test_volume_between_2_7_litres
    assert_volume "around 2 -7 l", 2.0, "litre"
    assert_volume "~2-7 liters", 2.0, "litre"
    assert_volume "from 2 to 7 l", 2.0, "litre"
    assert_volume "between 2.0 l and about 7.0 l", 2.0, "litre"
    assert_volume "between 2l and about 7l", 2.0, "litre"
    assert_volume "2 - ~7 litres", 2.0, "litre"
  end

  # volume_corpus.rs:149
  def test_volume_under_6_gallons
    assert_volume "less than six gallons", 6.0, "gallon"
    assert_volume "under six gallon", 6.0, "gallon"
    assert_volume "no more than 6 gals", 6.0, "gallon"
    assert_volume "below 6.0gal", 6.0, "gallon"
    assert_volume "at most six gallons", 6.0, "gallon"
  end

  # volume_corpus.rs:159
  def test_volume_above_2_hectolitres
    assert_volume "exceeding 2 hectoliters", 2.0, "hectolitre"
    assert_volume "at least two hectolitres", 2.0, "hectolitre"
    assert_volume "over 2 hectolitre", 2.0, "hectolitre"
    assert_volume "more than 2 hectoliter", 2.0, "hectolitre"
  end

  # volume_corpus.rs:168
  def test_volume_above_4_ml
    assert_volume "exceeding 4 ml", 4.0, "millilitre"
    assert_volume "at least 4.0 ml", 4.0, "millilitre"
    assert_volume "over four milliliters", 4.0, "millilitre"
    assert_volume "more than four mls", 4.0, "millilitre"
  end
end
